module.exports = [
	{ name: 'Jan 95 to Apr 95', sets: [ 'Revised', 'The_Dark', 'Fallen_Empires']},
	{ name: 'Apr 95 to Jun 95', sets: [ 'Fourth_Edition', 'The_Dark', 'Fallen_Empires']},
	{ name: 'Jun 95 to Jul 95', sets: [ 'Fourth_Edition', 'Fallen_Empires', 'Ice_Age']},
	{ name: 'Aug 95 to Sep 95', sets: [ 'Fourth_Edition', 'Fallen_Empires', 'Ice_Age', 'Chronicles']},
	{ name: 'Oct 95 to Jun 96', sets: [ 'Fourth_Edition', 'Chronicles', 'Fallen_Empires', 'Ice_Age', 'Homelands']},
	{ name: 'Jun 96 to Sep 96', sets: [ 'Fourth_Edition', 'Chronicles', 'Fallen_Empires', 'Ice_Age', 'Homelands', 'Alliances']},
	{ name: 'Oct 96 to Dec 96', sets: [ 'Fourth_Edition', 'Chronicles', 'Fallen_Empires', 'Ice_Age', 'Homelands', 'Alliances', 'Mirage']},
	{ name: 'Jan 97 to Mar 97', sets: [ 'Fourth_Edition', 'Chronicles', 'Homelands', 'Alliances', 'Mirage']},
	{ name: 'Mar 97 to Apr 97', sets: [ 'Fourth_Edition', 'Chronicles', 'Alliances', 'Mirage', 'Visions']},
	{ name: 'Apr 97 to Jun 97', sets: [ 'Alliances', 'Mirage', 'Visions', 'Fifth_Edition']},
	{ name: 'Jul 97 to Oct 97', sets: [ 'Ice_Age', 'Homelands', 'Alliances', 'Fifth_Edition', 'Mirage', 'Visions', 'Weatherlight']},
	{ name: 'Nov 97 to Mar 98', sets: [ 'Fifth_Edition', 'Mirage', 'Visions', 'Weatherlight', 'Tempest']},
	{ name: 'Apr 98 to Jun 98', sets: [ 'Fifth_Edition', 'Mirage', 'Visions', 'Weatherlight', 'Tempest', 'Stronghold']},
	{ name: 'Jul 98 to Oct 98', sets: [ 'Fifth_Edition', 'Mirage', 'Visions', 'Weatherlight', 'Tempest', 'Stronghold', 'Exodus']},
	{ name: 'Nov 98 to Feb 99', sets: [ 'Fifth_Edition', 'Tempest', 'Stronghold', 'Exodus', 'Urzas_Saga']},
	{ name: 'Mar 99 to May 99', sets: [ 'Fifth_Edition', 'Tempest', 'Stronghold', 'Exodus', 'Urzas_Saga', 'Urzas_Legacy']},
	{ name: 'Jun 99 to Jun 99', sets: [ 'Tempest', 'Stronghold', 'Exodus', 'Urzas_Saga', 'Urzas_Legacy', 'Sixth_Edition']},
	{ name: 'July 99 to Oct 99', sets: [ 'Tempest', 'Stronghold', 'Exodus', 'Urzas_Saga', 'Urzas_Legacy', 'Sixth_Edition', 'Urzas_Destiny']},
	{ name: 'Nov 99 to Feb 00', sets: [ 'Urzas_Saga', 'Urzas_Legacy', 'Sixth_Edition', 'Urzas_Destiny', 'Mercadian_Masques']},
	{ name: 'Mar 00 to Jun 00', sets: [ 'Urzas_Saga', 'Urzas_Legacy', 'Sixth_Edition', 'Urzas_Destiny', 'Mercadian_Masques', 'Nemesis']},
	{ name: 'Jul 00 to Oct 00', sets: [ 'Urzas_Saga', 'Urzas_Legacy', 'Sixth_Edition', 'Urzas_Destiny', 'Mercadian_Masques', 'Nemesis', 'Prophecy']},
	{ name: 'Nov 00 to Feb 01', sets: [ 'Sixth_Edition', 'Mercadian_Masques', 'Nemesis', 'Prophecy', 'Invasion']},
	{ name: 'Mar 01 to Apr 01', sets: [ 'Sixth_Edition', 'Mercadian_Masques', 'Nemesis', 'Prophecy', 'Invasion', 'Planeshift']},
	{ name: 'May 01 to Jun 01', sets: [ 'Mercadian_Masques', 'Nemesis', 'Prophecy', 'Invasion', 'Planeshift', 'Seventh_Edition']},
	{ name: 'Jul 01 to Oct 01', sets: [ 'Mercadian_Masques', 'Nemesis', 'Prophecy', 'Invasion', 'Planeshift', 'Seventh_Edition', 'Apocalypse']},
	{ name: 'Nov 01 to Feb 02', sets: [ 'Invasion', 'Planeshift', 'Seventh_Edition', 'Apocalypse', 'Odyssey']},
	{ name: 'Mar 02 to Jun 02', sets: [ 'Invasion', 'Planeshift', 'Seventh_Edition', 'Apocalypse', 'Odyssey', 'Torment']},
	{ name: 'Jul 02 to Oct 02', sets: [ 'Invasion', 'Planeshift', 'Seventh_Edition', 'Apocalypse', 'Odyssey', 'Torment', 'Judgement']},
	{ name: 'Nov 02 to Feb 03', sets: [ 'Seventh_Edition', 'Odyssey', 'Torment', 'Judgement', 'Onslaught']},
	{ name: 'Mar 03 to Jun 03', sets: [ 'Seventh_Edition', 'Odyssey', 'Torment', 'Judgement', 'Onslaught', 'Legions']},
	{ name: 'Jul 03 to Aug 03', sets: [ 'Seventh_Edition', 'Odyssey', 'Torment', 'Judgement', 'Onslaught', 'Legions', 'Scourge']},
	{ name: 'Sep 03 to Oct 03', sets: [ 'Odyssey', 'Torment', 'Judgement', 'Onslaught', 'Legions', 'Scourge', 'Eighth_Edition']},
	{ name: 'Oct 03 to Feb 04', sets: [ 'Onslaught', 'Legions', 'Scourge', 'Eighth_Edition', 'Mirrodin']},
	{ name: 'Feb 04 to Jun 04', sets: [ 'Onslaught', 'Legions', 'Scourge', 'Eighth_Edition', 'Mirrodin', 'Darksteel']},
	{ name: 'Jun 04 to Oct 04', sets: [ 'Onslaught', 'Legions', 'Scourge', 'Eighth_Edition', 'Mirrodin', 'Darksteel', 'Fifth_Dawn']},
	{ name: 'Oct 04 to Feb 05', sets: [ 'Eighth_Edition', 'Mirrodin', 'Darksteel', 'Fifth_Dawn', 'Champions_of_Kamigawa']},
	{ name: 'Feb 05 to Jun 05', sets: [ 'Eighth_Edition', 'Mirrodin', 'Darksteel', 'Fifth_Dawn', 'Champions_of_Kamigawa', 'Betrayers_of_Kamigawa']},
	{ name: 'Jun 05 to Aug 05', sets: [ 'Eighth_Edition', 'Mirrodin', 'Darksteel', 'Fifth_Dawn', 'Champions_of_Kamigawa', 'Betrayers_of_Kamigawa', 'Saviors_of_Kamigawa']},
	{ name: 'Aug 05 to Oct 05', sets: [ 'Mirrodin', 'Darksteel', 'Fifth_Dawn', 'Champions_of_Kamigawa', 'Betrayers_of_Kamigawa', 'Saviors_of_Kamigawa', 'Ninth_Edition']},
	{ name: 'Oct 05 to Feb 06', sets: [ 'Champions_of_Kamigawa', 'Betrayers_of_Kamigawa', 'Saviors_of_Kamigawa', 'Ninth_Edition', 'Ravnica__City_of_Guilds']},
	{ name: 'Feb 06 to May 06', sets: [ 'Champions_of_Kamigawa', 'Betrayers_of_Kamigawa', 'Saviors_of_Kamigawa', 'Ninth_Edition', 'Ravnica__City_of_Guilds', 'Guildpact']},
	{ name: 'May 06 to Aug 06', sets: [ 'Champions_of_Kamigawa', 'Betrayers_of_Kamigawa', 'Saviors_of_Kamigawa', 'Ninth_Edition', 'Ravnica__City_of_Guilds', 'Guildpact', 'Dissention']},
	{ name: 'Aug 06 to Oct 06', sets: [ 'Champions_of_Kamigawa', 'Betrayers_of_Kamigawa', 'Saviors_of_Kamigawa', 'Ninth_Edition', 'Ravnica__City_of_Guilds', 'Guildpact', 'Dissention', 'Coldsnap']},
	{ name: 'Oct 06 to Feb 07', sets: [ 'Ninth_Edition', 'Ravnica__City_of_Guilds', 'Guildpact', 'Dissention', 'Coldsnap', 'Time_Spiral']},
	{ name: 'Feb 07 to May 07', sets: [ 'Ninth_Edition', 'Ravnica__City_of_Guilds', 'Guildpact', 'Dissention', 'Coldsnap', 'Time_Spiral', 'Planar_Chaos']},
	{ name: 'May 07 to July 07', sets: [ 'Ninth_Edition', 'Ravnica__City_of_Guilds', 'Guildpact', 'Dissention', 'Coldsnap', 'Time_Spiral', 'Planar_Chaos', 'Future_Sight']},
	{ name: 'July 07 to Oct 07', sets: [ 'Ninth_Edition', 'Ravnica__City_of_Guilds', 'Guildpact', 'Dissention', 'Coldsnap', 'Time_Spiral', 'Planar_Chaos', 'Future_Sight', 'Tenth_Edition']},
	{ name: 'Oct 07 to Jan 08', sets: [ 'Coldsnap', 'Time_Spiral', 'Planar_Chaos', 'Future_Sight', 'Tenth_Edition', 'Lorwyn']},
	{ name: 'Feb 08 to May 08', sets: [ 'Coldsnap', 'Time_Spiral', 'Planar_Chaos', 'Future_Sight', 'Tenth_Edition', 'Lorwyn', 'Morningtide']},
	{ name: 'May 08 to July 08', sets: [ 'Coldsnap', 'Time_Spiral', 'Planar_Chaos', 'Future_Sight', 'Tenth_Edition', 'Lorwyn', 'Morningtide', 'Shadowmoor']},
	{ name: 'July 08 to Oct 08', sets: [ 'Coldsnap', 'Time_Spiral', 'Planar_Chaos', 'Future_Sight', 'Tenth_Edition', 'Lorwyn', 'Morningtide', 'Shadowmoor', 'Eventide']},
	{ name: 'Oct 08 to Feb 09', sets: [ 'Tenth_Edition', 'Lorwyn', 'Morningtide', 'Shadowmoor', 'Eventide', 'Shards_of_Alara']},
	{ name: 'Feb 09 to Apr 09', sets: [ 'Tenth_Edition', 'Lorwyn', 'Morningtide', 'Shadowmoor', 'Eventide', 'Shards_of_Alara', 'Conflux']},
	{ name: 'Apr 30 to Jul 09', sets: [ 'Tenth_Edition', 'Lorwyn', 'Morningtide', 'Shadowmoor', 'Eventide', 'Shards_of_Alara', 'Conflux', 'Alara_Reborn']},
	{ name: 'Jul 09 to Oct 09', sets: [ 'Lorwyn', 'Morningtide', 'Shadowmoor', 'Eventide', 'Shards_of_Alara', 'Conflux', 'Alara_Reborn', 'Magic_2010']},
	{ name: 'Oct 09 to Feb 10', sets: [ 'Shards_of_Alara', 'Conflux', 'Alara_Reborn', 'Magic_2010', 'Zendikar']},
	{ name: 'Feb 10 to Apr 10', sets: [ 'Shards_of_Alara', 'Conflux', 'Alara_Reborn', 'Magic_2010', 'Zendikar', 'Worldwake']},
	{ name: 'Apr 10 to Jul 10', sets: [ 'Shards_of_Alara', 'Conflux', 'Alara_Reborn', 'Magic_2010', 'Zendikar', 'Worldwake', 'Rise_of_the_Eldrazi']},
	{ name: 'Jul 10 to Sep 10', sets: [ 'Shards_of_Alara', 'Conflux', 'Alara_Reborn', 'Magic_2010', 'Zendikar', 'Worldwake', 'Rise_of_the_Eldrazi', 'Magic_2011']},
	{ name: 'Oct 10 to Feb 11', sets: [ 'Zendikar', 'Worldwake', 'Rise_of_the_Eldrazi', 'Magic_2011', 'Scars_of_Mirrodin']},
	{ name: 'Feb 11 to May 11', sets: [ 'Zendikar', 'Worldwake', 'Rise_of_the_Eldrazi', 'Magic_2011', 'Scars_of_Mirrodin', 'Mirrodin_Besieged']},
	{ name: 'May 11 to Jul 11', sets: [ 'Zendikar', 'Worldwake', 'Rise_of_the_Eldrazi', 'Magic_2011', 'Scars_of_Mirrodin', 'Mirrodin_Besieged', 'New_Phyrexia']},
	{ name: 'Jul 11 to Sep 11', sets: [ 'Zendikar', 'Worldwake', 'Rise_of_the_Eldrazi', 'Magic_2011', 'Scars_of_Mirrodin', 'Mirrodin_Besieged', 'New_Phyrexia', 'Magic_2012']},
	{ name: 'Sep 11 to Feb 11', sets: [ 'Scars_of_Mirrodin', 'Mirrodin_Besieged', 'New_Phyrexia', 'Magic_2012', 'Innistad']},
	{ name: 'Feb 12 to May 12', sets: [ 'Scars_of_Mirrodin', 'Mirrodin_Besieged', 'New_Phyrexia', 'Magic_2012', 'Innistad', 'Dark_Ascension']},
	{ name: 'May 12 to Jul 12', sets: [ 'Scars_of_Mirrodin', 'Mirrodin_Besieged', 'New_Phyrexia', 'Magic_2012', 'Innistad', 'Dark_Ascension', 'Avacyn_Restored']},
	{ name: 'Jul 12 to Oct 12', sets: [ 'Scars_of_Mirrodin', 'Mirrodin_Besieged', 'New_Phyrexia', 'Magic_2012', 'Innistad', 'Dark_Ascension', 'Avacyn_Restored', 'Magic_2013']},
	{ name: 'Oct 12 to Jan 13', sets: [ 'Innistad', 'Dark_Ascension', 'Avacyn_Restored', 'Magic_2013', 'Return_to_Ravnica']},
	{ name: 'Feb 13 to May 13', sets: [ 'Innistad', 'Dark_Ascension', 'Avacyn_Restored', 'Magic_2013', 'Return_to_Ravnica', 'Gatecrash']},
	{ name: 'May 13 to Jul 13', sets: [ 'Innistad', 'Dark_Ascension', 'Avacyn_Restored', 'Magic_2013', 'Return_to_Ravnica', 'Gatecrash', 'Dragons_Maze']},
	{ name: 'Jul 13 to Sep 13', sets: [ 'Innistad', 'Dark_Ascension', 'Avacyn_Restored', 'Magic_2013', 'Return_to_Ravnica', 'Gatecrash', 'Dragons_Maze', 'Magic_2014']},
	{ name: 'Sep 13 to Feb 14', sets: [ 'Return_to_Ravnica', 'Gatecrash', 'Dragons_Maze', 'Magic_2014', 'Theros']},
	{ name: 'Feb 14 to May 14', sets: [ 'Return_to_Ravnica', 'Gatecrash', 'Dragons_Maze', 'Magic_2014', 'Theros', 'Born_of_the_Gods']},
	{ name: 'May 14 to Jul 14', sets: [ 'Return_to_Ravnica', 'Gatecrash', 'Dragons_Maze', 'Magic_2014', 'Theros', 'Born_of_the_Gods', 'Journey_into_Nyx']},
	{ name: 'Jul 14 to Sep 14', sets: [ 'Return_to_Ravnica', 'Gatecrash', 'Dragons_Maze', 'Magic_2014', 'Theros', 'Born_of_the_Gods', 'Journey_into_Nyx', 'Magic_2015']},
	{ name: 'Sep 14 to Jan 15', sets: [ 'Theros', 'Born_of_the_Gods', 'Journey_into_Nyx', 'Magic_2015', 'Khans_of_Tarkir']},
	{ name: 'Jan 15 to Mar 15', sets: [ 'Theros', 'Born_of_the_Gods', 'Journey_into_Nyx', 'Magic_2015', 'Khans_of_Tarkir', 'Fate_Reforged']},
	{ name: 'Mar 15 to Jul 15', sets: [ 'Theros', 'Born_of_the_Gods', 'Journey_into_Nyx', 'Magic_2015', 'Khans_of_Tarkir', 'Fate_Reforged', 'Dragons_of_Tarkir']},
	{ name: 'Jul 15 to Oct 15', sets: [ 'Theros', 'Born_of_the_Gods', 'Journey_into_Nyx', 'Magic_2015', 'Khans_of_Tarkir', 'Fate_Reforged', 'Dragons_of_Tarkir', 'Magic_Origins']},
	{ name: 'Oct 15 to Jan 16', sets: [ 'Khans_of_Tarkir', 'Fate_Reforged', 'Dragons_of_Tarkir', 'Magic_Origins', 'Battle_for_Zendikar']},
	{ name: 'Jan 16 to Apr 16', sets: [ 'Khans_of_Tarkir', 'Fate_Reforged', 'Dragons_of_Tarkir', 'Magic_Origins', 'Battle_for_Zendikar', 'Oath_of_the_Gatwatch']},
	{ name: 'Apr 16 to Jul 16', sets: [ 'Dragons_of_Tarkir', 'Magic_Origins', 'Battle_for_Zendikar', 'Oath_of_the_Gatwatch', 'Shadows_over_Innistrad']},
	{ name: 'Jul 16 to Sep 16', sets: [ 'Dragons_of_Tarkir', 'Magic_Origins', 'Battle_for_Zendikar', 'Oath_of_the_Gatwatch', 'Shadows_over_Innistrad', 'Eldritch_Moon']},
	{ name: 'Sep 16 to Jan 17', sets: [ 'Battle_for_Zendikar', 'Oath_of_the_Gatwatch', 'Shadows_over_Innistrad', 'Eldritch_Moon', 'Kaladesh']},
	{ name: 'Jan 17 to Apr 17', sets: [ 'Battle_for_Zendikar', 'Oath_of_the_Gatwatch', 'Shadows_over_Innistrad', 'Eldritch_Moon', 'Kaladesh', 'Aether_Revolt']},
	{ name: 'Apr 17 to Jun 17', sets: [ 'Battle_for_Zendikar', 'Oath_of_the_Gatwatch', 'Shadows_over_Innistrad', 'Eldritch_Moon', 'Kaladesh', 'Aether_Revolt', 'Amonkhet']},
	{ name: 'Jun 17 to Sep 17', sets: [ 'Battle_for_Zendikar', 'Oath_of_the_Gatwatch', 'Shadows_over_Innistrad', 'Eldritch_Moon', 'Kaladesh', 'Aether_Revolt', 'Amonkhet', 'Hour_of_Devastation']},
	{ name: 'Sep 17 to Jan 18', sets: [ 'Kaladesh', 'Aether_Revolt', 'Amonkhet', 'Hour_of_Devastation', 'Ixalan']},
	{ name: 'Jan 18 to Apr 18', sets: [ 'Kaladesh', 'Aether_Revolt', 'Amonkhet', 'Hour_of_Devastation', 'Ixalan', 'Rivals_of_Ixalan']},
	{ name: 'Apr 18 to Jul 18', sets: [ 'Kaladesh', 'Aether_Revolt', 'Amonkhet', 'Hour_of_Devastation', 'Ixalan', 'Rivals_of_Ixalan', 'Dominaria']},
	{ name: 'Jul 18 to Oct 18', sets: [ 'Kaladesh', 'Aether_Revolt', 'Amonkhet', 'Hour_of_Devastation', 'Ixalan', 'Rivals_of_Ixalan', 'Dominaria', 'Core_Set_2019']},
	{ name: 'Oct 18 to Jan 19', sets: [ 'Ixalan', 'Rivals_of_Ixalan', 'Dominaria', 'Core_Set_2019', 'Guilds_of_Ravnica']},
	{ name: 'Jan 19 to Apr 19', sets: [ 'Ixalan', 'Rivals_of_Ixalan', 'Dominaria', 'Core_Set_2019', 'Guilds_of_Ravnica', 'Ravnica_Allegiance']}
]
