module.exports = [ { object: 'card',
    id: '75e49715-e5b6-475d-ab50-ddc5ff729c11',
    oracle_id: 'eac25f12-6459-438c-a09e-93e23d2cf80d',
    multiverse_ids: [],
    tcgplayer_id: 82612,
    name: 'Soldier',
    lang: 'en',
    released_at: '2013-01-01',
    uri:
     'https://api.scryfall.com/cards/75e49715-e5b6-475d-ab50-ddc5ff729c11',
    scryfall_uri: 'https://scryfall.com/card/l13/4/soldier?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/l13/4.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/l13/4.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/l13/4.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/l13/4.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/l13/4.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/l13/4.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Soldier',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [ 'W' ],
    color_identity: [ 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: false,
    reprint: true,
    set: 'l13',
    set_name: 'League Tokens 2013',
    set_uri:
     'https://api.scryfall.com/sets/ff250c63-a900-4154-8b39-0bdeb03edabc',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Al13&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/l13?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/75e49715-e5b6-475d-ab50-ddc5ff729c11/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aeac25f12-6459-438c-a09e-93e23d2cf80d&unique=prints',
    collector_number: '4',
    digital: false,
    rarity: 'common',
    illustration_id: 'c138c1aa-fdad-46aa-b9f9-730f754b48c7',
    artist: 'Zoltan Boros',
    border_color: 'black',
    frame: '2003',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Soldier&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Soldier',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Soldier' },
    myId: 2 },
  { object: 'card',
    id: '50c4f43e-ed03-43de-8ff1-2d4431c1684a',
    oracle_id: '9ac81d75-2bec-46ab-84e1-2fc893d45219',
    multiverse_ids: [],
    tcgplayer_id: 78526,
    name: 'Sliver',
    lang: 'en',
    released_at: '2013-01-01',
    uri:
     'https://api.scryfall.com/cards/50c4f43e-ed03-43de-8ff1-2d4431c1684a',
    scryfall_uri: 'https://scryfall.com/card/l13/3/sliver?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/l13/3.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/l13/3.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/l13/3.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/l13/3.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/l13/3.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/l13/3.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Sliver',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [],
    color_identity: [],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: false,
    reprint: false,
    set: 'l13',
    set_name: 'League Tokens 2013',
    set_uri:
     'https://api.scryfall.com/sets/ff250c63-a900-4154-8b39-0bdeb03edabc',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Al13&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/l13?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/50c4f43e-ed03-43de-8ff1-2d4431c1684a/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A9ac81d75-2bec-46ab-84e1-2fc893d45219&unique=prints',
    collector_number: '3',
    digital: false,
    rarity: 'common',
    illustration_id: '2910d045-3afc-4e1c-a119-66c6fb22ef61',
    artist: 'Vincent Proce',
    border_color: 'black',
    frame: '2003',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Sliver&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Sliver',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Sliver' },
    myId: 3 },
  { object: 'card',
    id: '3fb27481-e7c8-43e3-a1f1-06dcffb70154',
    oracle_id: 'b1a2b096-a440-4ef9-ab2a-059c79999297',
    multiverse_ids: [],
    tcgplayer_id: 108436,
    name: 'Bird',
    lang: 'en',
    released_at: '2013-01-01',
    uri:
     'https://api.scryfall.com/cards/3fb27481-e7c8-43e3-a1f1-06dcffb70154',
    scryfall_uri: 'https://scryfall.com/card/l13/2/bird?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/l13/2.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/l13/2.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/l13/2.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/l13/2.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/l13/2.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/l13/2.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Bird',
    oracle_text: 'Flying',
    power: '1',
    toughness: '1',
    colors: [ 'W' ],
    color_identity: [ 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: false,
    reprint: true,
    set: 'l13',
    set_name: 'League Tokens 2013',
    set_uri:
     'https://api.scryfall.com/sets/ff250c63-a900-4154-8b39-0bdeb03edabc',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Al13&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/l13?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/3fb27481-e7c8-43e3-a1f1-06dcffb70154/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ab1a2b096-a440-4ef9-ab2a-059c79999297&unique=prints',
    collector_number: '2',
    digital: false,
    rarity: 'common',
    illustration_id: 'd9065910-dac4-4a01-a668-f490d047567e',
    artist: 'Martina Pilcerova',
    border_color: 'black',
    frame: '2003',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Bird&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Bird',
       mtgtop8: 'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Bird' },
    myId: 4 },
  { object: 'card',
    id: 'd651b974-24f2-4c5d-a3bc-94b802b3b90c',
    oracle_id: '04ba3865-3e4b-4583-b49b-f5433926c29a',
    multiverse_ids: [],
    tcgplayer_id: 78444,
    name: 'Soldier',
    lang: 'en',
    released_at: '2013-01-01',
    uri:
     'https://api.scryfall.com/cards/d651b974-24f2-4c5d-a3bc-94b802b3b90c',
    scryfall_uri: 'https://scryfall.com/card/l13/1/soldier?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/l13/1.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/l13/1.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/l13/1.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/l13/1.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/l13/1.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/l13/1.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Soldier',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [ 'R', 'W' ],
    color_identity: [ 'R', 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: false,
    reprint: false,
    set: 'l13',
    set_name: 'League Tokens 2013',
    set_uri:
     'https://api.scryfall.com/sets/ff250c63-a900-4154-8b39-0bdeb03edabc',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Al13&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/l13?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/d651b974-24f2-4c5d-a3bc-94b802b3b90c/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A04ba3865-3e4b-4583-b49b-f5433926c29a&unique=prints',
    collector_number: '1',
    digital: false,
    rarity: 'common',
    illustration_id: 'b4f84c3e-9e2d-4935-a1dc-84fc3cceb602',
    artist: 'Johann Bodin',
    border_color: 'black',
    frame: '2003',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Soldier&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Soldier',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Soldier' },
    myId: 5 } ]