module.exports = [ { object: 'card',
    id: '12856d0c-240f-42c6-80dd-715ccf314645',
    oracle_id: '6a880a0f-0a98-4505-9c27-9821be3e4818',
    multiverse_ids: [],
    tcgplayer_id: 108438,
    name: 'Warrior',
    lang: 'en',
    released_at: '2014-01-01',
    uri:
     'https://api.scryfall.com/cards/12856d0c-240f-42c6-80dd-715ccf314645',
    scryfall_uri: 'https://scryfall.com/card/l14/4/warrior?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/l14/4.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/l14/4.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/l14/4.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/l14/4.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/l14/4.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/l14/4.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Warrior',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [ 'W' ],
    color_identity: [ 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: false,
    reprint: false,
    set: 'l14',
    set_name: 'League Tokens 2014',
    set_uri:
     'https://api.scryfall.com/sets/2a314e02-ee9d-453b-84a2-92cf55135ee6',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Al14&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/l14?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/12856d0c-240f-42c6-80dd-715ccf314645/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A6a880a0f-0a98-4505-9c27-9821be3e4818&unique=prints',
    collector_number: '4',
    digital: false,
    rarity: 'common',
    illustration_id: '8967e39b-90f2-4f53-8ff5-979ae9a64b79',
    artist: 'Winona Nelson',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Warrior&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Warrior',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Warrior' },
    myId: 2 },
  { object: 'card',
    id: '8084eae3-6b2a-4803-9959-1fc5c80500de',
    oracle_id: 'dd85fcd6-9bfd-4deb-a56a-77c6bca8eb97',
    multiverse_ids: [],
    tcgplayer_id: 108433,
    name: 'Squid',
    lang: 'en',
    released_at: '2014-01-01',
    uri:
     'https://api.scryfall.com/cards/8084eae3-6b2a-4803-9959-1fc5c80500de',
    scryfall_uri: 'https://scryfall.com/card/l14/3/squid?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/l14/3.jpg?1546828614',
       normal:
        'https://img.scryfall.com/cards/normal/en/l14/3.jpg?1546828614',
       large:
        'https://img.scryfall.com/cards/large/en/l14/3.jpg?1546828614',
       png: 'https://img.scryfall.com/cards/png/en/l14/3.png?1546828614',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/l14/3.jpg?1546828614',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/l14/3.jpg?1546828614' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Squid',
    oracle_text: 'Islandwalk',
    power: '1',
    toughness: '1',
    colors: [ 'U' ],
    color_identity: [ 'U' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: false,
    reprint: false,
    set: 'l14',
    set_name: 'League Tokens 2014',
    set_uri:
     'https://api.scryfall.com/sets/2a314e02-ee9d-453b-84a2-92cf55135ee6',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Al14&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/l14?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/8084eae3-6b2a-4803-9959-1fc5c80500de/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Add85fcd6-9bfd-4deb-a56a-77c6bca8eb97&unique=prints',
    collector_number: '3',
    digital: false,
    rarity: 'common',
    illustration_id: '477f58bb-b561-4c68-9fdb-c2dda198d657',
    artist: 'Richard Wright',
    border_color: 'black',
    frame: '2015',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Squid&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Squid',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Squid' },
    myId: 3 },
  { object: 'card',
    id: '62a8926c-94d7-4399-ad38-f235bbfd1a7e',
    oracle_id: '6b8117bf-384f-4f5e-9e52-e01412ce24a9',
    multiverse_ids: [],
    tcgplayer_id: 108434,
    name: 'Minotaur',
    lang: 'en',
    released_at: '2014-01-01',
    uri:
     'https://api.scryfall.com/cards/62a8926c-94d7-4399-ad38-f235bbfd1a7e',
    scryfall_uri: 'https://scryfall.com/card/l14/2/minotaur?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/l14/2.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/l14/2.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/l14/2.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/l14/2.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/l14/2.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/l14/2.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Minotaur',
    oracle_text: '',
    power: '2',
    toughness: '3',
    colors: [ 'R' ],
    color_identity: [ 'R' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: false,
    reprint: false,
    set: 'l14',
    set_name: 'League Tokens 2014',
    set_uri:
     'https://api.scryfall.com/sets/2a314e02-ee9d-453b-84a2-92cf55135ee6',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Al14&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/l14?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/62a8926c-94d7-4399-ad38-f235bbfd1a7e/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A6b8117bf-384f-4f5e-9e52-e01412ce24a9&unique=prints',
    collector_number: '2',
    digital: false,
    rarity: 'common',
    illustration_id: '2457378c-ff71-4871-b972-56b5fceeb1f2',
    artist: 'Scott Murphy',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Minotaur&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Minotaur',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Minotaur' },
    myId: 4 },
  { object: 'card',
    id: '0a7c8ad6-b6c6-41ef-939b-ce3ec261a50b',
    oracle_id: 'cca22679-fb67-4a43-b824-0f8faac0f319',
    multiverse_ids: [],
    tcgplayer_id: 108437,
    name: 'Soldier',
    lang: 'en',
    released_at: '2014-01-01',
    uri:
     'https://api.scryfall.com/cards/0a7c8ad6-b6c6-41ef-939b-ce3ec261a50b',
    scryfall_uri: 'https://scryfall.com/card/l14/1/soldier?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/l14/1.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/l14/1.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/l14/1.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/l14/1.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/l14/1.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/l14/1.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Enchantment Creature — Soldier',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [ 'W' ],
    color_identity: [ 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: false,
    reprint: false,
    set: 'l14',
    set_name: 'League Tokens 2014',
    set_uri:
     'https://api.scryfall.com/sets/2a314e02-ee9d-453b-84a2-92cf55135ee6',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Al14&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/l14?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/0a7c8ad6-b6c6-41ef-939b-ce3ec261a50b/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Acca22679-fb67-4a43-b824-0f8faac0f319&unique=prints',
    collector_number: '1',
    digital: false,
    rarity: 'common',
    illustration_id: 'c6889d28-6b19-4ac1-9e4a-2824eedd42ad',
    artist: 'Ryan Barger',
    border_color: 'black',
    frame: '2003',
    frame_effect: 'nyxtouched',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Soldier&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Soldier',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Soldier' },
    myId: 5 } ]