module.exports = [ { object: 'card',
    id: '46b60d95-b9bc-40f8-b986-bfa8e3eb74f3',
    oracle_id: '6a7a9dff-ff9e-4005-a17f-6ea0c11c1d5a',
    multiverse_ids: [],
    tcgplayer_id: 78633,
    name: 'Spirit',
    lang: 'en',
    released_at: '2004-01-01',
    uri:
     'https://api.scryfall.com/cards/46b60d95-b9bc-40f8-b986-bfa8e3eb74f3',
    scryfall_uri: 'https://scryfall.com/card/p04/6/spirit?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p04/6.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p04/6.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p04/6.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p04/6.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p04/6.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p04/6.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Spirit',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [],
    color_identity: [],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p04',
    set_name: 'Magic Player Rewards 2004',
    set_uri:
     'https://api.scryfall.com/sets/5ba81c6d-2344-4760-bb13-b7276205e73e',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap04&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p04?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/46b60d95-b9bc-40f8-b986-bfa8e3eb74f3/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A6a7a9dff-ff9e-4005-a17f-6ea0c11c1d5a&unique=prints',
    collector_number: '6',
    digital: false,
    rarity: 'common',
    illustration_id: 'a24db34c-adab-42ae-865d-1df62e1bd221',
    artist: 'Hugh Jamieson',
    border_color: 'black',
    frame: '2003',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Spirit&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Spirit',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Spirit' },
    myId: 2 },
  { object: 'card',
    id: 'd02d5670-fff3-4011-8e45-e6843e4e8988',
    oracle_id: '6bb61f34-5d57-4eaa-a02c-f5d08c1ee920',
    multiverse_ids: [],
    tcgplayer_id: 78616,
    name: 'Beast',
    lang: 'en',
    released_at: '2004-01-01',
    uri:
     'https://api.scryfall.com/cards/d02d5670-fff3-4011-8e45-e6843e4e8988',
    scryfall_uri: 'https://scryfall.com/card/p04/5/beast?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p04/5.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p04/5.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p04/5.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p04/5.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p04/5.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p04/5.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Beast',
    oracle_text: '',
    power: '3',
    toughness: '3',
    colors: [ 'G' ],
    color_identity: [ 'G' ],
    all_parts:
     [ { object: 'related_card',
         id: 'd02d5670-fff3-4011-8e45-e6843e4e8988',
         component: 'token',
         name: 'Beast',
         type_line: 'Token Creature — Beast',
         uri:
          'https://api.scryfall.com/cards/d02d5670-fff3-4011-8e45-e6843e4e8988' },
       { object: 'related_card',
         id: '9fc04b19-e636-4868-8224-a5da75ea01c8',
         component: 'token',
         name: 'Wurm',
         type_line: 'Token Creature — Wurm',
         uri:
          'https://api.scryfall.com/cards/9fc04b19-e636-4868-8224-a5da75ea01c8' } ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p04',
    set_name: 'Magic Player Rewards 2004',
    set_uri:
     'https://api.scryfall.com/sets/5ba81c6d-2344-4760-bb13-b7276205e73e',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap04&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p04?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/d02d5670-fff3-4011-8e45-e6843e4e8988/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A6bb61f34-5d57-4eaa-a02c-f5d08c1ee920&unique=prints',
    collector_number: '5',
    digital: false,
    rarity: 'common',
    illustration_id: 'd2970c33-7006-4c2a-95fb-ec3c3dbe8ca1',
    artist: 'Edward P. Beard, Jr.',
    border_color: 'black',
    frame: '2003',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Beast&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Beast',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Beast' },
    myId: 3 },
  { object: 'card',
    id: '187cf6d5-c352-48f2-b8bf-fe1bf946e2ac',
    oracle_id: 'bf690282-125f-431c-a363-39f6772324c8',
    multiverse_ids: [],
    tcgplayer_id: 78626,
    name: 'Myr',
    lang: 'en',
    released_at: '2004-01-01',
    uri:
     'https://api.scryfall.com/cards/187cf6d5-c352-48f2-b8bf-fe1bf946e2ac',
    scryfall_uri: 'https://scryfall.com/card/p04/4/myr?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p04/4.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p04/4.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p04/4.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p04/4.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p04/4.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p04/4.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Artifact Creature — Myr',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [],
    color_identity: [],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p04',
    set_name: 'Magic Player Rewards 2004',
    set_uri:
     'https://api.scryfall.com/sets/5ba81c6d-2344-4760-bb13-b7276205e73e',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap04&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p04?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/187cf6d5-c352-48f2-b8bf-fe1bf946e2ac/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Abf690282-125f-431c-a363-39f6772324c8&unique=prints',
    collector_number: '4',
    digital: false,
    rarity: 'common',
    illustration_id: 'b4482da5-2b7a-44d0-8446-fb0ea007adf3',
    artist: 'Wayne England',
    border_color: 'black',
    frame: '2003',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Myr&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Myr',
       mtgtop8: 'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Myr' },
    myId: 4 },
  { object: 'card',
    id: '4fbb0dc6-2f9e-4389-8a90-531e94009bfb',
    oracle_id: 'c9e57f97-be25-4ab6-9158-d2677d7742f7',
    multiverse_ids: [],
    tcgplayer_id: 78627,
    name: 'Pentavite',
    lang: 'en',
    released_at: '2004-01-01',
    uri:
     'https://api.scryfall.com/cards/4fbb0dc6-2f9e-4389-8a90-531e94009bfb',
    scryfall_uri: 'https://scryfall.com/card/p04/3/pentavite?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p04/3.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p04/3.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p04/3.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p04/3.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p04/3.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p04/3.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Artifact Creature — Pentavite',
    oracle_text: 'Flying',
    power: '1',
    toughness: '1',
    colors: [],
    color_identity: [],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p04',
    set_name: 'Magic Player Rewards 2004',
    set_uri:
     'https://api.scryfall.com/sets/5ba81c6d-2344-4760-bb13-b7276205e73e',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap04&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p04?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/4fbb0dc6-2f9e-4389-8a90-531e94009bfb/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ac9e57f97-be25-4ab6-9158-d2677d7742f7&unique=prints',
    collector_number: '3',
    digital: false,
    rarity: 'common',
    illustration_id: '27378cca-8d9e-433d-8994-f374bb87b3ed',
    artist: 'Greg Staples',
    border_color: 'black',
    frame: '2003',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Pentavite&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Pentavite',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Pentavite' },
    myId: 5 },
  { object: 'card',
    id: 'c7f3264a-7b4a-4fef-af73-d4241742a4e8',
    oracle_id: '40c64f08-ab2f-4933-8e0e-d1a1c729008f',
    multiverse_ids: [],
    tcgplayer_id: 78613,
    name: 'Angel',
    lang: 'en',
    released_at: '2004-01-01',
    uri:
     'https://api.scryfall.com/cards/c7f3264a-7b4a-4fef-af73-d4241742a4e8',
    scryfall_uri: 'https://scryfall.com/card/p04/2/angel?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p04/2.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p04/2.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p04/2.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p04/2.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p04/2.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p04/2.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Angel',
    oracle_text: 'Flying',
    power: '4',
    toughness: '4',
    colors: [ 'W' ],
    color_identity: [ 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p04',
    set_name: 'Magic Player Rewards 2004',
    set_uri:
     'https://api.scryfall.com/sets/5ba81c6d-2344-4760-bb13-b7276205e73e',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap04&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p04?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/c7f3264a-7b4a-4fef-af73-d4241742a4e8/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A40c64f08-ab2f-4933-8e0e-d1a1c729008f&unique=prints',
    collector_number: '2',
    digital: false,
    rarity: 'common',
    illustration_id: '6c72b80e-6584-407a-9408-e655314c8642',
    artist: 'Scott M. Fischer',
    border_color: 'black',
    frame: '2003',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Angel&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Angel',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Angel' },
    myId: 6 },
  { object: 'card',
    id: '2b77caf8-711b-4597-a5a5-dead81568e5b',
    oracle_id: 'ca1144c2-49a3-49b4-9085-3094141769ea',
    multiverse_ids: [],
    tcgplayer_id: 38328,
    name: 'Powder Keg',
    lang: 'en',
    released_at: '2004-01-01',
    uri:
     'https://api.scryfall.com/cards/2b77caf8-711b-4597-a5a5-dead81568e5b',
    scryfall_uri: 'https://scryfall.com/card/p04/1/powder-keg?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p04/1.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p04/1.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p04/1.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p04/1.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p04/1.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p04/1.jpg?1517813031' },
    mana_cost: '{2}',
    cmc: 2,
    type_line: 'Artifact',
    oracle_text:
     'At the beginning of your upkeep, you may put a fuse counter on Powder Keg.\n{T}, Sacrifice Powder Keg: Destroy each artifact and creature with converted mana cost equal to the number of fuse counters on Powder Keg.',
    colors: [],
    color_identity: [],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       duel: 'legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: true,
    foil: true,
    nonfoil: false,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p04',
    set_name: 'Magic Player Rewards 2004',
    set_uri:
     'https://api.scryfall.com/sets/5ba81c6d-2344-4760-bb13-b7276205e73e',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap04&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p04?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/2b77caf8-711b-4597-a5a5-dead81568e5b/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aca1144c2-49a3-49b4-9085-3094141769ea&unique=prints',
    collector_number: '1',
    digital: false,
    rarity: 'rare',
    watermark: 'dci',
    illustration_id: 'fe4cf815-8b8b-4aaf-afb1-54992203bdcd',
    artist: 'Dan Frazier',
    border_color: 'black',
    frame: '2003',
    full_art: false,
    story_spotlight: false,
    edhrec_rank: 10898,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Powder+Keg&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Powder+Keg',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Powder+Keg' },
    myId: 7 } ]