module.exports = [ { object: 'card',
    id: 'b5489e26-6aec-4706-9c3e-8454878fa6c3',
    oracle_id: 'b8df27be-118b-4a76-95ec-9d6220314533',
    multiverse_ids: [],
    tcgplayer_id: 78628,
    name: 'Rukh',
    lang: 'en',
    released_at: '2003-01-01',
    uri:
     'https://api.scryfall.com/cards/b5489e26-6aec-4706-9c3e-8454878fa6c3',
    scryfall_uri: 'https://scryfall.com/card/p03/7/rukh?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p03/7.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p03/7.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p03/7.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p03/7.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p03/7.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p03/7.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Rukh',
    oracle_text: 'Flying',
    power: '4',
    toughness: '4',
    colors: [ 'R' ],
    color_identity: [ 'R' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: false,
    set: 'p03',
    set_name: 'Magic Player Rewards 2003',
    set_uri:
     'https://api.scryfall.com/sets/dfa906ff-63d8-4065-abef-809988337288',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap03&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p03?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/b5489e26-6aec-4706-9c3e-8454878fa6c3/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ab8df27be-118b-4a76-95ec-9d6220314533&unique=prints',
    collector_number: '7',
    digital: false,
    rarity: 'common',
    illustration_id: 'e5c22622-785b-49f9-a06c-0401a9aa43ce',
    artist: 'Edward P. Beard, Jr.',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Rukh&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Rukh',
       mtgtop8: 'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Rukh' },
    myId: 2 },
  { object: 'card',
    id: '084c3292-c3ec-431e-b162-309b5cf6309e',
    oracle_id: '0f6d78a4-f330-47b5-9c30-51324a1e7fb9',
    multiverse_ids: [],
    tcgplayer_id: 78619,
    name: 'Demon',
    lang: 'en',
    released_at: '2003-01-01',
    uri:
     'https://api.scryfall.com/cards/084c3292-c3ec-431e-b162-309b5cf6309e',
    scryfall_uri: 'https://scryfall.com/card/p03/6/demon?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p03/6.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p03/6.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p03/6.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p03/6.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p03/6.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p03/6.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Demon',
    oracle_text: 'Flying',
    power: '*',
    toughness: '*',
    colors: [ 'B' ],
    color_identity: [ 'B' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p03',
    set_name: 'Magic Player Rewards 2003',
    set_uri:
     'https://api.scryfall.com/sets/dfa906ff-63d8-4065-abef-809988337288',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap03&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p03?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/084c3292-c3ec-431e-b162-309b5cf6309e/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A0f6d78a4-f330-47b5-9c30-51324a1e7fb9&unique=prints',
    collector_number: '6',
    digital: false,
    rarity: 'common',
    illustration_id: '19b6883b-45f8-43a2-90e9-8285a1c5eafd',
    artist: 'Pete Venters',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Demon&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Demon',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Demon' },
    myId: 3 },
  { object: 'card',
    id: '08ca3900-3845-40ac-8581-d4aebc2850a0',
    oracle_id: '4465eff4-5851-4721-a248-866c686c2ab8',
    multiverse_ids: [],
    tcgplayer_id: 78623,
    name: 'Goblin',
    lang: 'en',
    released_at: '2003-01-01',
    uri:
     'https://api.scryfall.com/cards/08ca3900-3845-40ac-8581-d4aebc2850a0',
    scryfall_uri: 'https://scryfall.com/card/p03/5/goblin?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p03/5.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p03/5.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p03/5.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p03/5.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p03/5.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p03/5.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Goblin',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [ 'R' ],
    color_identity: [ 'R' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p03',
    set_name: 'Magic Player Rewards 2003',
    set_uri:
     'https://api.scryfall.com/sets/dfa906ff-63d8-4065-abef-809988337288',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap03&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p03?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/08ca3900-3845-40ac-8581-d4aebc2850a0/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A4465eff4-5851-4721-a248-866c686c2ab8&unique=prints',
    collector_number: '5',
    digital: false,
    rarity: 'common',
    flavor_text:
     'Never underestimate the power of overwhelming stupidity in overwhelming numbers.',
    illustration_id: 'a4828e3c-c18f-4015-bf7c-4277951b0280',
    artist: 'Darrell Riche',
    border_color: 'black',
    frame: '1997',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Goblin&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Goblin',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Goblin' },
    myId: 4 },
  { object: 'card',
    id: '6e1fc8db-f4a3-4f9c-bfab-64d5a3968435',
    oracle_id: 'a62a374d-ccdd-418d-9bcd-5ca8bf9b05e8',
    multiverse_ids: [],
    tcgplayer_id: 78615,
    name: 'Bear',
    lang: 'en',
    released_at: '2003-01-01',
    uri:
     'https://api.scryfall.com/cards/6e1fc8db-f4a3-4f9c-bfab-64d5a3968435',
    scryfall_uri: 'https://scryfall.com/card/p03/4/bear?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p03/4.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p03/4.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p03/4.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p03/4.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p03/4.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p03/4.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Bear',
    oracle_text: '',
    power: '2',
    toughness: '2',
    colors: [ 'G' ],
    color_identity: [ 'G' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p03',
    set_name: 'Magic Player Rewards 2003',
    set_uri:
     'https://api.scryfall.com/sets/dfa906ff-63d8-4065-abef-809988337288',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap03&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p03?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/6e1fc8db-f4a3-4f9c-bfab-64d5a3968435/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aa62a374d-ccdd-418d-9bcd-5ca8bf9b05e8&unique=prints',
    collector_number: '4',
    digital: false,
    rarity: 'common',
    flavor_text:
     "Bears get vicious when they don't sleep. This one hasn't slept in ages.",
    illustration_id: 'e31f6754-175d-4985-96bd-74e8c350b87c',
    artist: 'Glen Angus',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Bear&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Bear',
       mtgtop8: 'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Bear' },
    myId: 5 },
  { object: 'card',
    id: 'f3b8ae33-f0c3-4fe7-8121-41307d13bb4a',
    oracle_id: '9ac81d75-2bec-46ab-84e1-2fc893d45219',
    multiverse_ids: [],
    tcgplayer_id: 78630,
    name: 'Sliver',
    lang: 'en',
    released_at: '2003-01-01',
    uri:
     'https://api.scryfall.com/cards/f3b8ae33-f0c3-4fe7-8121-41307d13bb4a',
    scryfall_uri: 'https://scryfall.com/card/p03/3/sliver?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p03/3.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p03/3.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p03/3.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p03/3.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p03/3.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p03/3.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Sliver',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [],
    color_identity: [],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p03',
    set_name: 'Magic Player Rewards 2003',
    set_uri:
     'https://api.scryfall.com/sets/dfa906ff-63d8-4065-abef-809988337288',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap03&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p03?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/f3b8ae33-f0c3-4fe7-8121-41307d13bb4a/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A9ac81d75-2bec-46ab-84e1-2fc893d45219&unique=prints',
    collector_number: '3',
    digital: false,
    rarity: 'common',
    flavor_text: "Slivers don't learn. They just know.",
    illustration_id: 'b41c5151-36bd-4734-91a9-992e43f6a7bc',
    artist: 'Tony Szczudlo',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Sliver&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Sliver',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Sliver' },
    myId: 6 },
  { object: 'card',
    id: 'aa47df37-f246-4f80-a944-008cdf347dad',
    oracle_id: 'c39cd31f-c4a2-4ca8-b4f9-b2e6289743bc',
    multiverse_ids: [],
    tcgplayer_id: 78625,
    name: 'Insect',
    lang: 'en',
    released_at: '2003-01-01',
    uri:
     'https://api.scryfall.com/cards/aa47df37-f246-4f80-a944-008cdf347dad',
    scryfall_uri: 'https://scryfall.com/card/p03/2/insect?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p03/2.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p03/2.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p03/2.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p03/2.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p03/2.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p03/2.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Insect',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [ 'G' ],
    color_identity: [ 'G' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p03',
    set_name: 'Magic Player Rewards 2003',
    set_uri:
     'https://api.scryfall.com/sets/dfa906ff-63d8-4065-abef-809988337288',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap03&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p03?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/aa47df37-f246-4f80-a944-008cdf347dad/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ac39cd31f-c4a2-4ca8-b4f9-b2e6289743bc&unique=prints',
    collector_number: '2',
    digital: false,
    rarity: 'common',
    flavor_text: 'If insects could talk, the world would be deafened.',
    illustration_id: '608dbe4d-c1dc-45fc-aa80-02b9451a12e6',
    artist: 'Anthony S. Waters',
    border_color: 'black',
    frame: '1997',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Insect&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Insect',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Insect' },
    myId: 7 },
  { object: 'card',
    id: '4bdc1632-6824-4059-a6bd-bce9cd4a02f4',
    oracle_id: '7e2cacae-2934-4ff5-81c6-dfce7a2820ef',
    multiverse_ids: [],
    tcgplayer_id: 38342,
    name: 'Voidmage Prodigy',
    lang: 'en',
    released_at: '2003-01-01',
    uri:
     'https://api.scryfall.com/cards/4bdc1632-6824-4059-a6bd-bce9cd4a02f4',
    scryfall_uri:
     'https://scryfall.com/card/p03/1/voidmage-prodigy?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p03/1.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p03/1.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p03/1.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p03/1.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p03/1.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p03/1.jpg?1517813031' },
    mana_cost: '{U}{U}',
    cmc: 2,
    type_line: 'Creature — Human Wizard',
    oracle_text:
     '{U}{U}, Sacrifice a Wizard: Counter target spell.\nMorph {U} (You may cast this card face down as a 2/2 creature for {3}. Turn it face up any time for its morph cost.)',
    power: '2',
    toughness: '1',
    colors: [ 'U' ],
    color_identity: [ 'U' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       duel: 'legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p03',
    set_name: 'Magic Player Rewards 2003',
    set_uri:
     'https://api.scryfall.com/sets/dfa906ff-63d8-4065-abef-809988337288',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap03&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p03?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/4bdc1632-6824-4059-a6bd-bce9cd4a02f4/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A7e2cacae-2934-4ff5-81c6-dfce7a2820ef&unique=prints',
    collector_number: '1',
    digital: false,
    rarity: 'rare',
    illustration_id: '2188b65b-aa4b-48ac-a2c0-5b548deb24b0',
    artist: 'Christopher Moeller',
    border_color: 'black',
    frame: '1997',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    edhrec_rank: 3353,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Voidmage+Prodigy&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Voidmage+Prodigy',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Voidmage+Prodigy' },
    myId: 8 } ]