module.exports = [ { object: 'card',
    id: 'be7ef1c2-a75e-47ef-8181-cb7933ac09d6',
    oracle_id: '5b38fafb-3999-46dc-928b-1677625c1943',
    multiverse_ids: [],
    tcgplayer_id: 38335,
    name: 'Recollect',
    lang: 'en',
    released_at: '2007-01-01',
    uri:
     'https://api.scryfall.com/cards/be7ef1c2-a75e-47ef-8181-cb7933ac09d6',
    scryfall_uri: 'https://scryfall.com/card/p07/7/recollect?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p07/7.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p07/7.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p07/7.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p07/7.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p07/7.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p07/7.jpg?1517813031' },
    mana_cost: '{2}{G}',
    cmc: 3,
    type_line: 'Sorcery',
    oracle_text: 'Return target card from your graveyard to your hand.',
    colors: [ 'G' ],
    color_identity: [ 'G' ],
    legalities:
     { standard: 'legal',
       future: 'legal',
       frontier: 'legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p07',
    set_name: 'Magic Player Rewards 2007',
    set_uri:
     'https://api.scryfall.com/sets/c1a38fe6-73f4-4414-897b-f1215a7c948f',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap07&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p07?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/be7ef1c2-a75e-47ef-8181-cb7933ac09d6/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A5b38fafb-3999-46dc-928b-1677625c1943&unique=prints',
    collector_number: '7',
    digital: false,
    rarity: 'rare',
    illustration_id: '1d4bf128-52e8-410b-a81e-95fdff6877d8',
    artist: 'Michael Sutfin',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 4138,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Recollect&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Recollect',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Recollect' },
    myId: 2 },
  { object: 'card',
    id: '07494030-c1a3-4135-be88-9f7ba68f814b',
    oracle_id: 'a7e97fa9-4b72-4548-b854-5be5f18a6f1a',
    multiverse_ids: [],
    tcgplayer_id: 38306,
    name: 'Disenchant',
    lang: 'en',
    released_at: '2007-01-01',
    uri:
     'https://api.scryfall.com/cards/07494030-c1a3-4135-be88-9f7ba68f814b',
    scryfall_uri: 'https://scryfall.com/card/p07/6/disenchant?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p07/6.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p07/6.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p07/6.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p07/6.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p07/6.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p07/6.jpg?1517813031' },
    mana_cost: '{1}{W}',
    cmc: 2,
    type_line: 'Instant',
    oracle_text: 'Destroy target artifact or enchantment.',
    colors: [ 'W' ],
    color_identity: [ 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p07',
    set_name: 'Magic Player Rewards 2007',
    set_uri:
     'https://api.scryfall.com/sets/c1a38fe6-73f4-4414-897b-f1215a7c948f',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap07&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p07?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/07494030-c1a3-4135-be88-9f7ba68f814b/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aa7e97fa9-4b72-4548-b854-5be5f18a6f1a&unique=prints',
    collector_number: '6',
    digital: false,
    rarity: 'rare',
    illustration_id: '54ed2009-82fe-459e-ba96-40e1e57fa80c',
    artist: 'Heather Hudson',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 1262,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Disenchant&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Disenchant',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Disenchant' },
    myId: 3 },
  { object: 'card',
    id: 'fd3e0bb9-5a68-4164-9968-366299fca8ce',
    oracle_id: '10c585c4-bf5b-4d8f-94a9-e9a5036a688f',
    multiverse_ids: [],
    tcgplayer_id: 38302,
    name: 'Cruel Edict',
    lang: 'en',
    released_at: '2007-01-01',
    uri:
     'https://api.scryfall.com/cards/fd3e0bb9-5a68-4164-9968-366299fca8ce',
    scryfall_uri: 'https://scryfall.com/card/p07/5/cruel-edict?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p07/5.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p07/5.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p07/5.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p07/5.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p07/5.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p07/5.jpg?1517813031' },
    mana_cost: '{1}{B}',
    cmc: 2,
    type_line: 'Sorcery',
    oracle_text: 'Target opponent sacrifices a creature.',
    colors: [ 'B' ],
    color_identity: [ 'B' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p07',
    set_name: 'Magic Player Rewards 2007',
    set_uri:
     'https://api.scryfall.com/sets/c1a38fe6-73f4-4414-897b-f1215a7c948f',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap07&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p07?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/fd3e0bb9-5a68-4164-9968-366299fca8ce/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A10c585c4-bf5b-4d8f-94a9-e9a5036a688f&unique=prints',
    collector_number: '5',
    digital: false,
    rarity: 'rare',
    illustration_id: '109eb745-535b-407d-945a-56ea66c9726c',
    artist: 'Steve Ellis',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 7320,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Cruel+Edict&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Cruel+Edict',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Cruel+Edict' },
    myId: 4 },
  { object: 'card',
    id: '1a380513-9eea-4ff9-bcc8-7a6b53c642c4',
    oracle_id: '7f221ad6-7ec4-483d-a6b5-1456c95c1cad',
    multiverse_ids: [],
    tcgplayer_id: 38329,
    name: 'Psionic Blast',
    lang: 'en',
    released_at: '2007-01-01',
    uri:
     'https://api.scryfall.com/cards/1a380513-9eea-4ff9-bcc8-7a6b53c642c4',
    scryfall_uri:
     'https://scryfall.com/card/p07/4/psionic-blast?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p07/4.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p07/4.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p07/4.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p07/4.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p07/4.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p07/4.jpg?1517813031' },
    mana_cost: '{2}{U}',
    cmc: 3,
    type_line: 'Instant',
    oracle_text:
     'Psionic Blast deals 4 damage to any target and 2 damage to you.',
    colors: [ 'U' ],
    color_identity: [ 'U' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p07',
    set_name: 'Magic Player Rewards 2007',
    set_uri:
     'https://api.scryfall.com/sets/c1a38fe6-73f4-4414-897b-f1215a7c948f',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap07&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p07?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/1a380513-9eea-4ff9-bcc8-7a6b53c642c4/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A7f221ad6-7ec4-483d-a6b5-1456c95c1cad&unique=prints',
    collector_number: '4',
    digital: false,
    rarity: 'rare',
    illustration_id: '29107495-9954-4163-b6ac-07b4839998f0',
    artist: 'Aleksi Briclot',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 9318,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Psionic+Blast&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Psionic+Blast',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Psionic+Blast' },
    myId: 5 },
  { object: 'card',
    id: 'a36a42b0-8216-4c99-a85f-22a520f31fd4',
    oracle_id: 'faa01ed1-ccfa-4e58-951f-cd81f9068027',
    multiverse_ids: [],
    tcgplayer_id: 38321,
    name: 'Mortify',
    lang: 'en',
    released_at: '2007-01-01',
    uri:
     'https://api.scryfall.com/cards/a36a42b0-8216-4c99-a85f-22a520f31fd4',
    scryfall_uri: 'https://scryfall.com/card/p07/3/mortify?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p07/3.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p07/3.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p07/3.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p07/3.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p07/3.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p07/3.jpg?1517813031' },
    mana_cost: '{1}{W}{B}',
    cmc: 3,
    type_line: 'Instant',
    oracle_text: 'Destroy target creature or enchantment.',
    colors: [ 'B', 'W' ],
    color_identity: [ 'B', 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p07',
    set_name: 'Magic Player Rewards 2007',
    set_uri:
     'https://api.scryfall.com/sets/c1a38fe6-73f4-4414-897b-f1215a7c948f',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap07&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p07?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/a36a42b0-8216-4c99-a85f-22a520f31fd4/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Afaa01ed1-ccfa-4e58-951f-cd81f9068027&unique=prints',
    collector_number: '3',
    digital: false,
    rarity: 'rare',
    illustration_id: 'b4f30529-94c9-4f6f-8c98-45e0b3882613',
    artist: 'Brian Snõddy',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 226,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Mortify&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Mortify',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Mortify' },
    myId: 6 },
  { object: 'card',
    id: 'c986d9d6-d274-4ba9-8695-bc7c2f8e8fed',
    oracle_id: '377d31b5-0a48-4d5b-91bd-b5a62d4f7899',
    multiverse_ids: [],
    tcgplayer_id: 38300,
    name: 'Condemn',
    lang: 'en',
    released_at: '2007-01-01',
    uri:
     'https://api.scryfall.com/cards/c986d9d6-d274-4ba9-8695-bc7c2f8e8fed',
    scryfall_uri: 'https://scryfall.com/card/p07/2/condemn?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p07/2.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p07/2.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p07/2.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p07/2.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p07/2.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p07/2.jpg?1517813031' },
    mana_cost: '{W}',
    cmc: 1,
    type_line: 'Instant',
    oracle_text:
     'Put target attacking creature on the bottom of its owner\'s library. Its controller gains life equal to its toughness.',
    colors: [ 'W' ],
    color_identity: [ 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p07',
    set_name: 'Magic Player Rewards 2007',
    set_uri:
     'https://api.scryfall.com/sets/c1a38fe6-73f4-4414-897b-f1215a7c948f',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap07&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p07?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/c986d9d6-d274-4ba9-8695-bc7c2f8e8fed/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A377d31b5-0a48-4d5b-91bd-b5a62d4f7899&unique=prints',
    collector_number: '2',
    digital: false,
    rarity: 'rare',
    illustration_id: '21017a87-32d9-4a45-802c-0dccf9dfc818',
    artist: 'Kev Walker',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 818,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Condemn&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Condemn',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Condemn' },
    myId: 7 },
  { object: 'card',
    id: '10c5810f-83f6-43bf-8ece-047be42d7d58',
    oracle_id: '34515b16-c9a4-4f98-8c77-416a7a523407',
    multiverse_ids: [],
    tcgplayer_id: 38345,
    name: 'Wrath of God',
    lang: 'en',
    released_at: '2007-01-01',
    uri:
     'https://api.scryfall.com/cards/10c5810f-83f6-43bf-8ece-047be42d7d58',
    scryfall_uri:
     'https://scryfall.com/card/p07/1/wrath-of-god?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p07/1.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p07/1.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p07/1.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p07/1.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p07/1.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p07/1.jpg?1517813031' },
    mana_cost: '{2}{W}{W}',
    cmc: 4,
    type_line: 'Sorcery',
    oracle_text: 'Destroy all creatures. They can\'t be regenerated.',
    colors: [ 'W' ],
    color_identity: [ 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: true,
    nonfoil: false,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p07',
    set_name: 'Magic Player Rewards 2007',
    set_uri:
     'https://api.scryfall.com/sets/c1a38fe6-73f4-4414-897b-f1215a7c948f',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap07&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p07?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/10c5810f-83f6-43bf-8ece-047be42d7d58/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A34515b16-c9a4-4f98-8c77-416a7a523407&unique=prints',
    collector_number: '1',
    digital: false,
    rarity: 'rare',
    illustration_id: '6813bd80-fa6c-4919-ac40-e719ae1235f6',
    artist: 'Ron Spencer',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 64,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Wrath+of+God&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Wrath+of+God',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Wrath+of+God' },
    myId: 8 } ]