module.exports = [ { object: 'card',
    id: '4b5549fa-ff74-44a9-8709-c407b1b89062',
    oracle_id: 'a88a1c53-7de3-423a-a95a-24ed5666ab96',
    multiverse_ids: [],
    tcgplayer_id: 38301,
    name: 'Corrupt',
    lang: 'en',
    released_at: '2008-01-01',
    uri:
     'https://api.scryfall.com/cards/4b5549fa-ff74-44a9-8709-c407b1b89062',
    scryfall_uri: 'https://scryfall.com/card/p08/7/corrupt?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p08/7.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p08/7.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p08/7.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p08/7.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p08/7.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p08/7.jpg?1517813031' },
    mana_cost: '{5}{B}',
    cmc: 6,
    type_line: 'Sorcery',
    oracle_text:
     'Corrupt deals damage to any target equal to the number of Swamps you control. You gain life equal to the damage dealt this way.',
    colors: [ 'B' ],
    color_identity: [ 'B' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'legal',
       vintage: 'legal',
       penny: 'legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p08',
    set_name: 'Magic Player Rewards 2008',
    set_uri:
     'https://api.scryfall.com/sets/6c1d0a31-b5d2-421d-95f4-5816382f764f',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap08&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p08?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/4b5549fa-ff74-44a9-8709-c407b1b89062/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aa88a1c53-7de3-423a-a95a-24ed5666ab96&unique=prints',
    collector_number: '7',
    digital: false,
    rarity: 'rare',
    illustration_id: '6ab0d613-bf7e-40c7-9a27-8841024ecba0',
    artist: 'Philip Straub',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 3686,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Corrupt&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Corrupt',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Corrupt' },
    myId: 2 },
  { object: 'card',
    id: '15813b4a-9eee-4724-97f3-c1b845cba330',
    oracle_id: '02090581-61aa-4348-ad57-451be8ee91c2',
    multiverse_ids: [],
    tcgplayer_id: 38325,
    name: 'Ponder',
    lang: 'en',
    released_at: '2008-01-01',
    uri:
     'https://api.scryfall.com/cards/15813b4a-9eee-4724-97f3-c1b845cba330',
    scryfall_uri: 'https://scryfall.com/card/p08/6/ponder?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p08/6.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p08/6.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p08/6.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p08/6.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p08/6.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p08/6.jpg?1517813031' },
    mana_cost: '{U}',
    cmc: 1,
    type_line: 'Sorcery',
    oracle_text:
     'Look at the top three cards of your library, then put them back in any order. You may shuffle your library.\nDraw a card.',
    colors: [ 'U' ],
    color_identity: [ 'U' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'banned',
       legacy: 'legal',
       pauper: 'legal',
       vintage: 'restricted',
       penny: 'not_legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p08',
    set_name: 'Magic Player Rewards 2008',
    set_uri:
     'https://api.scryfall.com/sets/6c1d0a31-b5d2-421d-95f4-5816382f764f',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap08&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p08?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/15813b4a-9eee-4724-97f3-c1b845cba330/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A02090581-61aa-4348-ad57-451be8ee91c2&unique=prints',
    collector_number: '6',
    digital: false,
    rarity: 'rare',
    illustration_id: '5314f596-18cd-4558-bdf8-93bd593a79fe',
    artist: 'Steve Argyle',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 75,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Ponder&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Ponder',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Ponder' },
    myId: 3 },
  { object: 'card',
    id: '509cfb76-ab85-4473-ab81-83f6f62eb54c',
    oracle_id: '7eff84f1-f772-497a-b350-bbc93d0230f7',
    multiverse_ids: [],
    tcgplayer_id: 38311,
    name: 'Harmonize',
    lang: 'en',
    released_at: '2008-01-01',
    uri:
     'https://api.scryfall.com/cards/509cfb76-ab85-4473-ab81-83f6f62eb54c',
    scryfall_uri: 'https://scryfall.com/card/p08/5/harmonize?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p08/5.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p08/5.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p08/5.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p08/5.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p08/5.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p08/5.jpg?1517813031' },
    mana_cost: '{2}{G}{G}',
    cmc: 4,
    type_line: 'Sorcery',
    oracle_text: 'Draw three cards.',
    colors: [ 'G' ],
    color_identity: [ 'G' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p08',
    set_name: 'Magic Player Rewards 2008',
    set_uri:
     'https://api.scryfall.com/sets/6c1d0a31-b5d2-421d-95f4-5816382f764f',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap08&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p08?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/509cfb76-ab85-4473-ab81-83f6f62eb54c/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A7eff84f1-f772-497a-b350-bbc93d0230f7&unique=prints',
    collector_number: '5',
    digital: false,
    rarity: 'rare',
    illustration_id: '3342409c-3d09-464e-a3d0-872aa7ea6800',
    artist: 'Vance Kovacs',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 195,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Harmonize&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Harmonize',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Harmonize' },
    myId: 4 },
  { object: 'card',
    id: '652b0ce3-293d-4599-8a04-9df01b9bc678',
    oracle_id: '948217ac-289e-455f-8c7c-519aa75fa345',
    multiverse_ids: [],
    tcgplayer_id: 38320,
    name: 'Mana Tithe',
    lang: 'en',
    released_at: '2008-01-01',
    uri:
     'https://api.scryfall.com/cards/652b0ce3-293d-4599-8a04-9df01b9bc678',
    scryfall_uri: 'https://scryfall.com/card/p08/4/mana-tithe?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p08/4.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p08/4.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p08/4.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p08/4.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p08/4.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p08/4.jpg?1517813031' },
    mana_cost: '{W}',
    cmc: 1,
    type_line: 'Instant',
    oracle_text: 'Counter target spell unless its controller pays {1}.',
    colors: [ 'W' ],
    color_identity: [ 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p08',
    set_name: 'Magic Player Rewards 2008',
    set_uri:
     'https://api.scryfall.com/sets/6c1d0a31-b5d2-421d-95f4-5816382f764f',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap08&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p08?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/652b0ce3-293d-4599-8a04-9df01b9bc678/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A948217ac-289e-455f-8c7c-519aa75fa345&unique=prints',
    collector_number: '4',
    digital: false,
    rarity: 'rare',
    illustration_id: 'f037af1a-2c5a-4a78-bfb2-5e41d91b1b20',
    artist: 'Donato Giancola',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 3288,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Mana+Tithe&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Mana+Tithe',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Mana+Tithe' },
    myId: 5 },
  { object: 'card',
    id: 'f09dd696-8dff-41dd-b510-b2ad4c5d6c36',
    oracle_id: 'd8fd7a34-8418-4e98-b79b-119c4348c667',
    multiverse_ids: [],
    tcgplayer_id: 38315,
    name: 'Incinerate',
    lang: 'en',
    released_at: '2008-01-01',
    uri:
     'https://api.scryfall.com/cards/f09dd696-8dff-41dd-b510-b2ad4c5d6c36',
    scryfall_uri: 'https://scryfall.com/card/p08/3/incinerate?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p08/3.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p08/3.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p08/3.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p08/3.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p08/3.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p08/3.jpg?1517813031' },
    mana_cost: '{1}{R}',
    cmc: 2,
    type_line: 'Instant',
    oracle_text:
     'Incinerate deals 3 damage to any target. A creature dealt damage this way can\'t be regenerated this turn.',
    colors: [ 'R' ],
    color_identity: [ 'R' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p08',
    set_name: 'Magic Player Rewards 2008',
    set_uri:
     'https://api.scryfall.com/sets/6c1d0a31-b5d2-421d-95f4-5816382f764f',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap08&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p08?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/f09dd696-8dff-41dd-b510-b2ad4c5d6c36/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ad8fd7a34-8418-4e98-b79b-119c4348c667&unique=prints',
    collector_number: '3',
    digital: false,
    rarity: 'rare',
    illustration_id: '020f4c92-3c44-4496-8a8a-f12025cea454',
    artist: 'Zoltan Boros & Gabor Szikszai',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 4507,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Incinerate&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Incinerate',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Incinerate' },
    myId: 6 },
  { object: 'card',
    id: '68d77020-b313-429f-9005-a36ecf8caa05',
    oracle_id: '72897780-094d-4a21-8b1c-419a9defd2fb',
    multiverse_ids: [],
    tcgplayer_id: 38340,
    name: 'Tidings',
    lang: 'en',
    released_at: '2008-01-01',
    uri:
     'https://api.scryfall.com/cards/68d77020-b313-429f-9005-a36ecf8caa05',
    scryfall_uri: 'https://scryfall.com/card/p08/2/tidings?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p08/2.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p08/2.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p08/2.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p08/2.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p08/2.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p08/2.jpg?1517813031' },
    mana_cost: '{3}{U}{U}',
    cmc: 5,
    type_line: 'Sorcery',
    oracle_text: 'Draw four cards.',
    colors: [ 'U' ],
    color_identity: [ 'U' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p08',
    set_name: 'Magic Player Rewards 2008',
    set_uri:
     'https://api.scryfall.com/sets/6c1d0a31-b5d2-421d-95f4-5816382f764f',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap08&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p08?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/68d77020-b313-429f-9005-a36ecf8caa05/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A72897780-094d-4a21-8b1c-419a9defd2fb&unique=prints',
    collector_number: '2',
    digital: false,
    rarity: 'rare',
    illustration_id: 'c60572ca-5ff7-43ec-b8a2-dc9cf6cf4d23',
    artist: 'Michael Komarck',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 4506,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Tidings&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Tidings',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Tidings' },
    myId: 7 },
  { object: 'card',
    id: '6c5823bb-d56d-4bed-ba3f-09bdd93c52dc',
    oracle_id: 'd57a8f0b-7989-4db5-8756-6f2690097252',
    multiverse_ids: [],
    tcgplayer_id: 38304,
    name: 'Damnation',
    lang: 'en',
    released_at: '2008-01-01',
    uri:
     'https://api.scryfall.com/cards/6c5823bb-d56d-4bed-ba3f-09bdd93c52dc',
    scryfall_uri: 'https://scryfall.com/card/p08/1/damnation?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p08/1.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p08/1.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p08/1.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p08/1.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p08/1.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p08/1.jpg?1517813031' },
    mana_cost: '{2}{B}{B}',
    cmc: 4,
    type_line: 'Sorcery',
    oracle_text: 'Destroy all creatures. They can\'t be regenerated.',
    colors: [ 'B' ],
    color_identity: [ 'B' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: true,
    nonfoil: false,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p08',
    set_name: 'Magic Player Rewards 2008',
    set_uri:
     'https://api.scryfall.com/sets/6c1d0a31-b5d2-421d-95f4-5816382f764f',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap08&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p08?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/6c5823bb-d56d-4bed-ba3f-09bdd93c52dc/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ad57a8f0b-7989-4db5-8756-6f2690097252&unique=prints',
    collector_number: '1',
    digital: false,
    rarity: 'rare',
    illustration_id: '6dba9431-6ad3-4a53-848a-e64c0215874f',
    artist: 'Ron Spencer',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 178,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Damnation&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Damnation',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Damnation' },
    myId: 8 } ]