module.exports = [ { object: 'card',
    id: '3f55274a-54f1-4ab2-90ae-8634073baf5f',
    oracle_id: 'ebdd29c0-2c33-4410-a05c-80ced58c7b81',
    multiverse_ids: [],
    tcgplayer_id: 38334,
    name: 'Reciprocate',
    lang: 'en',
    released_at: '2005-01-01',
    uri:
     'https://api.scryfall.com/cards/3f55274a-54f1-4ab2-90ae-8634073baf5f',
    scryfall_uri: 'https://scryfall.com/card/p05/6/reciprocate?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p05/6.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p05/6.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p05/6.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p05/6.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p05/6.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p05/6.jpg?1517813031' },
    mana_cost: '{W}',
    cmc: 1,
    type_line: 'Instant',
    oracle_text: 'Exile target creature that dealt damage to you this turn.',
    colors: [ 'W' ],
    color_identity: [ 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       duel: 'legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p05',
    set_name: 'Magic Player Rewards 2005',
    set_uri:
     'https://api.scryfall.com/sets/e7f182b7-cd28-46de-bce8-223e83a78ae0',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap05&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p05?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/3f55274a-54f1-4ab2-90ae-8634073baf5f/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aebdd29c0-2c33-4410-a05c-80ced58c7b81&unique=prints',
    collector_number: '6',
    digital: false,
    rarity: 'rare',
    illustration_id: '5e436e15-9d2d-4e79-8c6a-7552d6dde52f',
    artist: 'Jim Murray',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 7990,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Reciprocate&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Reciprocate',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Reciprocate' },
    myId: 2 },
  { object: 'card',
    id: 'dea41eb7-5828-4735-bca1-0dbb0fda04e3',
    oracle_id: 'c61fe162-2202-4e56-9ba0-393547f9875f',
    multiverse_ids: [],
    tcgplayer_id: 38319,
    name: 'Mana Leak',
    lang: 'en',
    released_at: '2005-01-01',
    uri:
     'https://api.scryfall.com/cards/dea41eb7-5828-4735-bca1-0dbb0fda04e3',
    scryfall_uri: 'https://scryfall.com/card/p05/5/mana-leak?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p05/5.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p05/5.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p05/5.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p05/5.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p05/5.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p05/5.jpg?1517813031' },
    mana_cost: '{1}{U}',
    cmc: 2,
    type_line: 'Instant',
    oracle_text: 'Counter target spell unless its controller pays {3}.',
    colors: [ 'U' ],
    color_identity: [ 'U' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       duel: 'legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p05',
    set_name: 'Magic Player Rewards 2005',
    set_uri:
     'https://api.scryfall.com/sets/e7f182b7-cd28-46de-bce8-223e83a78ae0',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap05&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p05?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/dea41eb7-5828-4735-bca1-0dbb0fda04e3/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ac61fe162-2202-4e56-9ba0-393547f9875f&unique=prints',
    collector_number: '5',
    digital: false,
    rarity: 'rare',
    illustration_id: '8efda6a2-25d1-4ad6-aa4c-9da0770335c2',
    artist: 'Christopher Rush',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 692,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Mana+Leak&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Mana+Leak',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Mana+Leak' },
    myId: 3 },
  { object: 'card',
    id: '96837aad-424c-4d25-9ec1-b3121e6ac9a6',
    oracle_id: '0ff78353-a26e-4b5a-948d-1c3b41d2dd1f',
    multiverse_ids: [],
    tcgplayer_id: 38324,
    name: 'Oxidize',
    lang: 'en',
    released_at: '2005-01-01',
    uri:
     'https://api.scryfall.com/cards/96837aad-424c-4d25-9ec1-b3121e6ac9a6',
    scryfall_uri: 'https://scryfall.com/card/p05/4/oxidize?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p05/4.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p05/4.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p05/4.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p05/4.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p05/4.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p05/4.jpg?1517813031' },
    mana_cost: '{G}',
    cmc: 1,
    type_line: 'Instant',
    oracle_text: "Destroy target artifact. It can't be regenerated.",
    colors: [ 'G' ],
    color_identity: [ 'G' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'legal',
       commander: 'legal',
       duel: 'legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p05',
    set_name: 'Magic Player Rewards 2005',
    set_uri:
     'https://api.scryfall.com/sets/e7f182b7-cd28-46de-bce8-223e83a78ae0',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap05&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p05?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/96837aad-424c-4d25-9ec1-b3121e6ac9a6/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A0ff78353-a26e-4b5a-948d-1c3b41d2dd1f&unique=prints',
    collector_number: '4',
    digital: false,
    rarity: 'rare',
    illustration_id: '423b69ad-283e-4419-97a3-f5379bf1a7b7',
    artist: 'Scott M. Fischer',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 11211,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Oxidize&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Oxidize',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Oxidize' },
    myId: 4 },
  { object: 'card',
    id: '7c11fcd9-abad-47c8-ae47-55750bc1c9de',
    oracle_id: 'aa7714b0-2bfb-458a-8ebf-37ec2c53383e',
    multiverse_ids: [],
    tcgplayer_id: 38308,
    name: 'Fireball',
    lang: 'en',
    released_at: '2005-01-01',
    uri:
     'https://api.scryfall.com/cards/7c11fcd9-abad-47c8-ae47-55750bc1c9de',
    scryfall_uri: 'https://scryfall.com/card/p05/3/fireball?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p05/3.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p05/3.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p05/3.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p05/3.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p05/3.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p05/3.jpg?1517813031' },
    mana_cost: '{X}{R}',
    cmc: 1,
    type_line: 'Sorcery',
    oracle_text:
     'This spell costs {1} more to cast for each target beyond the first.\nFireball deals X damage divided evenly, rounded down, among any number of targets.',
    colors: [ 'R' ],
    color_identity: [ 'R' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'legal',
       commander: 'legal',
       duel: 'legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p05',
    set_name: 'Magic Player Rewards 2005',
    set_uri:
     'https://api.scryfall.com/sets/e7f182b7-cd28-46de-bce8-223e83a78ae0',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap05&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p05?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/7c11fcd9-abad-47c8-ae47-55750bc1c9de/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aaa7714b0-2bfb-458a-8ebf-37ec2c53383e&unique=prints',
    collector_number: '3',
    digital: false,
    rarity: 'rare',
    illustration_id: '19e0998d-81b9-4dd4-9c7e-5d6ee3e434a4',
    artist: 'Mark Tedin',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 2186,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Fireball&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Fireball',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Fireball' },
    myId: 5 },
  { object: 'card',
    id: 'ba9d4863-75f2-4894-8033-e4ffebe0547a',
    oracle_id: 'b81f041d-98db-4408-9472-c483e4a502bc',
    multiverse_ids: [],
    tcgplayer_id: 38339,
    name: 'Terror',
    lang: 'en',
    released_at: '2005-01-01',
    uri:
     'https://api.scryfall.com/cards/ba9d4863-75f2-4894-8033-e4ffebe0547a',
    scryfall_uri: 'https://scryfall.com/card/p05/2/terror?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p05/2.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p05/2.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p05/2.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p05/2.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p05/2.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p05/2.jpg?1517813031' },
    mana_cost: '{1}{B}',
    cmc: 2,
    type_line: 'Instant',
    oracle_text:
     "Destroy target nonartifact, nonblack creature. It can't be regenerated.",
    colors: [ 'B' ],
    color_identity: [ 'B' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'legal',
       legacy: 'legal',
       pauper: 'legal',
       vintage: 'legal',
       penny: 'legal',
       commander: 'legal',
       duel: 'legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p05',
    set_name: 'Magic Player Rewards 2005',
    set_uri:
     'https://api.scryfall.com/sets/e7f182b7-cd28-46de-bce8-223e83a78ae0',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap05&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p05?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/ba9d4863-75f2-4894-8033-e4ffebe0547a/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ab81f041d-98db-4408-9472-c483e4a502bc&unique=prints',
    collector_number: '2',
    digital: false,
    rarity: 'rare',
    illustration_id: 'c33dbbd0-3709-4e2b-b737-a5eb8e046465',
    artist: 'Ron Spencer',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: true,
    story_spotlight: false,
    edhrec_rank: 4636,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Terror&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Terror',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Terror' },
    myId: 6 },
  { object: 'card',
    id: 'd4d067fb-f3c9-4fe0-8330-da5e566eae9c',
    oracle_id: 'd7c4da85-d1a5-4a27-812d-65d8ee1494dd',
    multiverse_ids: [],
    tcgplayer_id: 38330,
    name: 'Psychatog',
    lang: 'en',
    released_at: '2005-01-01',
    uri:
     'https://api.scryfall.com/cards/d4d067fb-f3c9-4fe0-8330-da5e566eae9c',
    scryfall_uri: 'https://scryfall.com/card/p05/1/psychatog?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/p05/1.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/p05/1.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/p05/1.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/p05/1.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/p05/1.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/p05/1.jpg?1517813031' },
    mana_cost: '{1}{U}{B}',
    cmc: 3,
    type_line: 'Creature — Atog',
    oracle_text:
     'Discard a card: Psychatog gets +1/+1 until end of turn.\nExile two cards from your graveyard: Psychatog gets +1/+1 until end of turn.',
    power: '1',
    toughness: '2',
    colors: [ 'B', 'U' ],
    color_identity: [ 'B', 'U' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'legal',
       commander: 'legal',
       duel: 'legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: true,
    nonfoil: false,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'p05',
    set_name: 'Magic Player Rewards 2005',
    set_uri:
     'https://api.scryfall.com/sets/e7f182b7-cd28-46de-bce8-223e83a78ae0',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ap05&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/p05?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/d4d067fb-f3c9-4fe0-8330-da5e566eae9c/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ad7c4da85-d1a5-4a27-812d-65d8ee1494dd&unique=prints',
    collector_number: '1',
    digital: false,
    rarity: 'rare',
    watermark: 'dci',
    illustration_id: 'f63e1a6c-b7b2-41be-91f0-ffe3f2877165',
    artist: 'Edward P. Beard, Jr.',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    edhrec_rank: 8854,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Psychatog&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Psychatog',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Psychatog' },
    myId: 7 } ]