module.exports = [ { object: 'card',
    id: '5b953ca2-5be4-4c6a-a0fd-b53219ca6341',
    oracle_id: 'eac25f12-6459-438c-a09e-93e23d2cf80d',
    multiverse_ids: [],
    tcgplayer_id: 78631,
    name: 'Soldier',
    lang: 'en',
    released_at: '2002-01-01',
    uri:
     'https://api.scryfall.com/cards/5b953ca2-5be4-4c6a-a0fd-b53219ca6341',
    scryfall_uri: 'https://scryfall.com/card/pr2/8/soldier?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/pr2/8.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/pr2/8.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/pr2/8.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/pr2/8.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/pr2/8.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/pr2/8.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Soldier',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [ 'W' ],
    color_identity: [ 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       '1v1': 'not_legal',
       duel: 'not_legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'pr2',
    set_name: 'Magic Player Rewards 2002',
    set_uri:
     'https://api.scryfall.com/sets/b3978acb-8a06-4362-b835-dbda8611a48c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Apr2&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/pr2?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/5b953ca2-5be4-4c6a-a0fd-b53219ca6341/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aeac25f12-6459-438c-a09e-93e23d2cf80d&unique=prints',
    collector_number: '8',
    digital: false,
    rarity: 'common',
    flavor_text: 'Duty brings them together. Loyalty keeps them together.',
    illustration_id: '064ee961-70bf-4087-9466-cb4107c2b5b8',
    artist: 'Ron Spencer',
    border_color: 'black',
    frame: '1997',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Soldier&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Soldier',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Soldier' },
    myId: 2 },
  { object: 'card',
    id: '56c0fa29-fbcb-41fe-94ab-a39b1154c99b',
    oracle_id: '60fe4897-6760-4c5a-8074-c92bd64df52b',
    multiverse_ids: [],
    tcgplayer_id: 78620,
    name: 'Dragon',
    lang: 'en',
    released_at: '2002-01-01',
    uri:
     'https://api.scryfall.com/cards/56c0fa29-fbcb-41fe-94ab-a39b1154c99b',
    scryfall_uri: 'https://scryfall.com/card/pr2/7/dragon?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/pr2/7.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/pr2/7.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/pr2/7.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/pr2/7.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/pr2/7.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/pr2/7.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Dragon',
    oracle_text: 'Flying',
    power: '5',
    toughness: '5',
    colors: [ 'R' ],
    color_identity: [ 'R' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       '1v1': 'not_legal',
       duel: 'not_legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'pr2',
    set_name: 'Magic Player Rewards 2002',
    set_uri:
     'https://api.scryfall.com/sets/b3978acb-8a06-4362-b835-dbda8611a48c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Apr2&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/pr2?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/56c0fa29-fbcb-41fe-94ab-a39b1154c99b/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A60fe4897-6760-4c5a-8074-c92bd64df52b&unique=prints',
    collector_number: '7',
    digital: false,
    rarity: 'common',
    flavor_text: 'Stars shine, winds blow, dragons rage.',
    illustration_id: '0784d260-5986-4147-bf78-cea1c1a9b537',
    artist: 'Glen Angus',
    border_color: 'black',
    frame: '1997',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Dragon&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Dragon',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Dragon' },
    myId: 3 },
  { object: 'card',
    id: '9fc04b19-e636-4868-8224-a5da75ea01c8',
    oracle_id: '46a55586-cc9a-443c-b458-e628afc3c587',
    multiverse_ids: [],
    tcgplayer_id: 78635,
    name: 'Wurm',
    lang: 'en',
    released_at: '2002-01-01',
    uri:
     'https://api.scryfall.com/cards/9fc04b19-e636-4868-8224-a5da75ea01c8',
    scryfall_uri: 'https://scryfall.com/card/pr2/6/wurm?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/pr2/6.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/pr2/6.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/pr2/6.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/pr2/6.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/pr2/6.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/pr2/6.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Wurm',
    oracle_text: '',
    power: '6',
    toughness: '6',
    colors: [ 'G' ],
    color_identity: [ 'G' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       '1v1': 'not_legal',
       duel: 'not_legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'pr2',
    set_name: 'Magic Player Rewards 2002',
    set_uri:
     'https://api.scryfall.com/sets/b3978acb-8a06-4362-b835-dbda8611a48c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Apr2&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/pr2?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/9fc04b19-e636-4868-8224-a5da75ea01c8/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A46a55586-cc9a-443c-b458-e628afc3c587&unique=prints',
    collector_number: '6',
    digital: false,
    rarity: 'common',
    flavor_text:
     'When wurms aren\'t hungry —Nantuko expression meaning "never"',
    illustration_id: 'cce56368-7d7a-4110-a9e1-dd19cd211e92',
    artist: 'Alan Pollack',
    border_color: 'black',
    frame: '1997',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Wurm&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Wurm',
       mtgtop8: 'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Wurm' },
    myId: 4 },
  { object: 'card',
    id: '3dc13cf6-665a-4d92-836f-b2e10ca08ecd',
    oracle_id: '079c46cc-feb0-4998-8593-c8b739afdb82',
    multiverse_ids: [],
    tcgplayer_id: 78622,
    name: 'Elephant',
    lang: 'en',
    released_at: '2002-01-01',
    uri:
     'https://api.scryfall.com/cards/3dc13cf6-665a-4d92-836f-b2e10ca08ecd',
    scryfall_uri: 'https://scryfall.com/card/pr2/5/elephant?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/pr2/5.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/pr2/5.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/pr2/5.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/pr2/5.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/pr2/5.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/pr2/5.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Elephant',
    oracle_text: '',
    power: '3',
    toughness: '3',
    colors: [ 'G' ],
    color_identity: [ 'G' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       '1v1': 'not_legal',
       duel: 'not_legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'pr2',
    set_name: 'Magic Player Rewards 2002',
    set_uri:
     'https://api.scryfall.com/sets/b3978acb-8a06-4362-b835-dbda8611a48c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Apr2&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/pr2?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/3dc13cf6-665a-4d92-836f-b2e10ca08ecd/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A079c46cc-feb0-4998-8593-c8b739afdb82&unique=prints',
    collector_number: '5',
    digital: false,
    rarity: 'common',
    flavor_text: 'When elephants thunder, death is lightning quick.',
    illustration_id: 'f343faf3-3fc1-4016-9bde-6b2cd73bae9f',
    artist: 'Arnie Swekel',
    border_color: 'black',
    frame: '1997',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Elephant&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Elephant',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Elephant' },
    myId: 5 },
  { object: 'card',
    id: '657fa00d-ddb5-49e6-a01e-82038cccfe30',
    oracle_id: 'ddc8c973-c31e-463f-be45-f3fa7d632362',
    multiverse_ids: [],
    tcgplayer_id: 78636,
    name: 'Zombie',
    lang: 'en',
    released_at: '2002-01-01',
    uri:
     'https://api.scryfall.com/cards/657fa00d-ddb5-49e6-a01e-82038cccfe30',
    scryfall_uri: 'https://scryfall.com/card/pr2/4/zombie?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/pr2/4.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/pr2/4.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/pr2/4.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/pr2/4.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/pr2/4.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/pr2/4.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Zombie',
    oracle_text: '',
    power: '2',
    toughness: '2',
    colors: [ 'B' ],
    color_identity: [ 'B' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       '1v1': 'not_legal',
       duel: 'not_legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'pr2',
    set_name: 'Magic Player Rewards 2002',
    set_uri:
     'https://api.scryfall.com/sets/b3978acb-8a06-4362-b835-dbda8611a48c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Apr2&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/pr2?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/657fa00d-ddb5-49e6-a01e-82038cccfe30/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Addc8c973-c31e-463f-be45-f3fa7d632362&unique=prints',
    collector_number: '4',
    digital: false,
    rarity: 'common',
    flavor_text:
     'The most battle-worn zombies are equal parts stitch and stench.',
    illustration_id: '816305fa-1555-42c8-96a3-e9c630c32af6',
    artist: 'Dana Knutson',
    border_color: 'black',
    frame: '1997',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Zombie&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Zombie',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Zombie' },
    myId: 6 },
  { object: 'card',
    id: 'af7c2def-d20d-4670-8950-7042e9380844',
    oracle_id: '67f21c0c-2083-4eda-9dc3-cc8aee42289f',
    multiverse_ids: [],
    tcgplayer_id: 78634,
    name: 'Squirrel',
    lang: 'en',
    released_at: '2002-01-01',
    uri:
     'https://api.scryfall.com/cards/af7c2def-d20d-4670-8950-7042e9380844',
    scryfall_uri: 'https://scryfall.com/card/pr2/3/squirrel?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/pr2/3.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/pr2/3.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/pr2/3.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/pr2/3.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/pr2/3.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/pr2/3.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Squirrel',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [ 'G' ],
    color_identity: [ 'G' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       '1v1': 'not_legal',
       duel: 'not_legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'pr2',
    set_name: 'Magic Player Rewards 2002',
    set_uri:
     'https://api.scryfall.com/sets/b3978acb-8a06-4362-b835-dbda8611a48c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Apr2&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/pr2?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/af7c2def-d20d-4670-8950-7042e9380844/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A67f21c0c-2083-4eda-9dc3-cc8aee42289f&unique=prints',
    collector_number: '3',
    digital: false,
    rarity: 'common',
    flavor_text: 'It\'s surprising how well cute and vicious go together.',
    illustration_id: '06d809f7-86ce-4806-946c-1aa9b74dcfa3',
    artist: 'Ron Spencer',
    border_color: 'black',
    frame: '1997',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Squirrel&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Squirrel',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Squirrel' },
    myId: 7 },
  { object: 'card',
    id: 'be349cd4-be71-4864-8f1d-4224fa41e6d1',
    oracle_id: '4692740f-be90-459f-8d90-c4ae71771595',
    multiverse_ids: [],
    name: 'Crusade',
    lang: 'en',
    released_at: '2002-01-01',
    uri:
     'https://api.scryfall.com/cards/be349cd4-be71-4864-8f1d-4224fa41e6d1',
    scryfall_uri: 'https://scryfall.com/card/pr2/2/crusade?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/pr2/2.jpg?1523720426',
       normal:
        'https://img.scryfall.com/cards/normal/en/pr2/2.jpg?1523720426',
       large:
        'https://img.scryfall.com/cards/large/en/pr2/2.jpg?1523720426',
       png: 'https://img.scryfall.com/cards/png/en/pr2/2.png?1523720426',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/pr2/2.jpg?1523720426',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/pr2/2.jpg?1523720426' },
    mana_cost: '{W}{W}',
    cmc: 2,
    type_line: 'Enchantment',
    oracle_text: 'White creatures get +1/+1.',
    colors: [ 'W' ],
    color_identity: [ 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: true,
    nonfoil: false,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'pr2',
    set_name: 'Magic Player Rewards 2002',
    set_uri:
     'https://api.scryfall.com/sets/b3978acb-8a06-4362-b835-dbda8611a48c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Apr2&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/pr2?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/be349cd4-be71-4864-8f1d-4224fa41e6d1/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A4692740f-be90-459f-8d90-c4ae71771595&unique=prints',
    collector_number: '2',
    digital: false,
    rarity: 'rare',
    illustration_id: 'c2406cb0-b3f9-4ba8-88a1-2b5db19b952f',
    artist: 'Mark Poole',
    border_color: 'black',
    frame: '1997',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    edhrec_rank: 4447,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Crusade&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Crusade',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Crusade' },
    myId: 8 },
  { object: 'card',
    id: '1b04fea2-ef5b-4311-bc52-8222f1501eac',
    oracle_id: '09a70ae8-3859-4a09-901d-dce063fa3b5f',
    multiverse_ids: [],
    name: 'Wasteland',
    lang: 'en',
    released_at: '2002-01-01',
    uri:
     'https://api.scryfall.com/cards/1b04fea2-ef5b-4311-bc52-8222f1501eac',
    scryfall_uri: 'https://scryfall.com/card/pr2/1/wasteland?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/pr2/1.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/pr2/1.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/pr2/1.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/pr2/1.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/pr2/1.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/pr2/1.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Land',
    oracle_text:
     '{T}: Add {C}.\n{T}, Sacrifice Wasteland: Destroy target nonbasic land.',
    colors: [],
    color_identity: [],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       '1v1': 'legal',
       duel: 'legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: true,
    nonfoil: false,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'pr2',
    set_name: 'Magic Player Rewards 2002',
    set_uri:
     'https://api.scryfall.com/sets/b3978acb-8a06-4362-b835-dbda8611a48c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Apr2&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/pr2?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/1b04fea2-ef5b-4311-bc52-8222f1501eac/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A09a70ae8-3859-4a09-901d-dce063fa3b5f&unique=prints',
    collector_number: '1',
    digital: false,
    rarity: 'rare',
    flavor_text:
     '"I will show you fear in a handful of dust." — T. S. Eliot, "The Waste Land"',
    illustration_id: '38cf1045-0520-4a67-a25e-dc7bb3acead6',
    artist: 'Una Fricker',
    border_color: 'black',
    frame: '1997',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    edhrec_rank: 357,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Wasteland&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Wasteland',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Wasteland' },
    myId: 9 } ]