module.exports = [ { object: 'card',
    id: 'ce45e037-5efb-4735-afee-12d7dc3127d1',
    oracle_id: '695b14a0-920a-47bd-bd4a-7989862cdd0a',
    multiverse_ids: [],
    tcgplayer_id: 78617,
    name: 'Beast',
    lang: 'en',
    released_at: '2001-01-01',
    uri:
     'https://api.scryfall.com/cards/ce45e037-5efb-4735-afee-12d7dc3127d1',
    scryfall_uri: 'https://scryfall.com/card/mpr/8/beast?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/mpr/8.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/mpr/8.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/mpr/8.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/mpr/8.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/mpr/8.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/mpr/8.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Beast',
    oracle_text: '',
    power: '4',
    toughness: '4',
    colors: [ 'G' ],
    color_identity: [ 'G' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'mpr',
    set_name: 'Magic Player Rewards 2001',
    set_uri:
     'https://api.scryfall.com/sets/84cd4f76-a638-41ac-8c60-3a82d8708b5c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ampr&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/mpr?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/ce45e037-5efb-4735-afee-12d7dc3127d1/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A695b14a0-920a-47bd-bd4a-7989862cdd0a&unique=prints',
    collector_number: '8',
    digital: false,
    rarity: 'common',
    flavor_text:
     'When the prey in Krosa no longer satisfied them, the beasts began to hunt their hunters.',
    illustration_id: 'd148ee56-5159-4c53-bb42-38636a9fc54e',
    artist: 'Larry Elmore',
    border_color: 'black',
    frame: '1997',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Beast&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Beast',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Beast' },
    myId: 2 },
  { object: 'card',
    id: '0a21bc37-6f21-4dda-a313-a0d75696f7fc',
    oracle_id: 'a62a374d-ccdd-418d-9bcd-5ca8bf9b05e8',
    multiverse_ids: [],
    tcgplayer_id: 78614,
    name: 'Bear',
    lang: 'en',
    released_at: '2001-01-01',
    uri:
     'https://api.scryfall.com/cards/0a21bc37-6f21-4dda-a313-a0d75696f7fc',
    scryfall_uri: 'https://scryfall.com/card/mpr/7/bear?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/mpr/7.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/mpr/7.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/mpr/7.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/mpr/7.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/mpr/7.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/mpr/7.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Bear',
    oracle_text: '',
    power: '2',
    toughness: '2',
    colors: [ 'G' ],
    color_identity: [ 'G' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'mpr',
    set_name: 'Magic Player Rewards 2001',
    set_uri:
     'https://api.scryfall.com/sets/84cd4f76-a638-41ac-8c60-3a82d8708b5c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ampr&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/mpr?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/0a21bc37-6f21-4dda-a313-a0d75696f7fc/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aa62a374d-ccdd-418d-9bcd-5ca8bf9b05e8&unique=prints',
    collector_number: '7',
    digital: false,
    rarity: 'common',
    flavor_text:
     'The last thing a poacher in the Krosan Forest hears is the brutal sound of claws tearing flesh.',
    illustration_id: 'ada13b1c-381b-4899-aa0f-8436af2e6a3d',
    artist: 'Heather Hudson',
    border_color: 'black',
    frame: '1997',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Bear&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Bear',
       mtgtop8: 'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Bear' },
    myId: 3 },
  { object: 'card',
    id: 'b3b52233-d240-4be5-bbde-b1e67367ede4',
    oracle_id: '7b646e97-6c1d-4b37-8e27-82c36f2561e9',
    multiverse_ids: [],
    tcgplayer_id: 78624,
    name: 'Goblin Soldier',
    lang: 'en',
    released_at: '2001-01-01',
    uri:
     'https://api.scryfall.com/cards/b3b52233-d240-4be5-bbde-b1e67367ede4',
    scryfall_uri:
     'https://scryfall.com/card/mpr/6/goblin-soldier?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/mpr/6.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/mpr/6.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/mpr/6.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/mpr/6.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/mpr/6.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/mpr/6.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Goblin Soldier',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [ 'R', 'W' ],
    color_identity: [ 'R', 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'mpr',
    set_name: 'Magic Player Rewards 2001',
    set_uri:
     'https://api.scryfall.com/sets/84cd4f76-a638-41ac-8c60-3a82d8708b5c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ampr&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/mpr?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/b3b52233-d240-4be5-bbde-b1e67367ede4/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A7b646e97-6c1d-4b37-8e27-82c36f2561e9&unique=prints',
    collector_number: '6',
    digital: false,
    rarity: 'common',
    flavor_text:
     'They rarely question their orders. Of course, they rarely understand them.',
    illustration_id: '0088bb04-44ec-41f9-a7e6-b55ed165ec68',
    artist: 'Ron Spears',
    border_color: 'black',
    frame: '1997',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Goblin+Soldier&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Goblin+Soldier',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Goblin+Soldier' },
    myId: 4 },
  { object: 'card',
    id: '14ef4815-3dfe-47b3-ad81-1506925280d3',
    oracle_id: 'dc4e2134-f0c2-49aa-9ea3-ebf83af1445c',
    multiverse_ids: [],
    tcgplayer_id: 78632,
    name: 'Spirit',
    lang: 'en',
    released_at: '2001-01-01',
    uri:
     'https://api.scryfall.com/cards/14ef4815-3dfe-47b3-ad81-1506925280d3',
    scryfall_uri: 'https://scryfall.com/card/mpr/5/spirit?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/mpr/5.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/mpr/5.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/mpr/5.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/mpr/5.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/mpr/5.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/mpr/5.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Spirit',
    oracle_text: 'Flying',
    power: '1',
    toughness: '1',
    colors: [ 'W' ],
    color_identity: [ 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'mpr',
    set_name: 'Magic Player Rewards 2001',
    set_uri:
     'https://api.scryfall.com/sets/84cd4f76-a638-41ac-8c60-3a82d8708b5c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ampr&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/mpr?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/14ef4815-3dfe-47b3-ad81-1506925280d3/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3Adc4e2134-f0c2-49aa-9ea3-ebf83af1445c&unique=prints',
    collector_number: '5',
    digital: false,
    rarity: 'common',
    flavor_text: 'The joy of rebirth overshadows the sadness of death.',
    illustration_id: '3be8e434-cd01-412b-a0a9-9db10670211c',
    artist: 'John Matson',
    border_color: 'black',
    frame: '1997',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Spirit&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Spirit',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Spirit' },
    myId: 5 },
  { object: 'card',
    id: '26e0e196-36e6-4d7a-a76b-1c2a18270267',
    oracle_id: '39593ebf-49ee-4a74-8498-952b43fa5127',
    multiverse_ids: [],
    tcgplayer_id: 78618,
    name: 'Bird',
    lang: 'en',
    released_at: '2001-01-01',
    uri:
     'https://api.scryfall.com/cards/26e0e196-36e6-4d7a-a76b-1c2a18270267',
    scryfall_uri: 'https://scryfall.com/card/mpr/4/bird?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/mpr/4.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/mpr/4.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/mpr/4.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/mpr/4.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/mpr/4.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/mpr/4.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Bird',
    oracle_text: 'Flying',
    power: '1',
    toughness: '1',
    colors: [ 'U' ],
    color_identity: [ 'U' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'mpr',
    set_name: 'Magic Player Rewards 2001',
    set_uri:
     'https://api.scryfall.com/sets/84cd4f76-a638-41ac-8c60-3a82d8708b5c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ampr&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/mpr?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/26e0e196-36e6-4d7a-a76b-1c2a18270267/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A39593ebf-49ee-4a74-8498-952b43fa5127&unique=prints',
    collector_number: '4',
    digital: false,
    rarity: 'common',
    flavor_text: "The landbound envy the birds' ultimate freedom in the sky.",
    illustration_id: 'f6e7d483-f7bb-4dc9-97e4-b9e8b97a6f60',
    artist: 'Michael Sutfin',
    border_color: 'black',
    frame: '1997',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Bird&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Bird',
       mtgtop8: 'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Bird' },
    myId: 6 },
  { object: 'card',
    id: '540a3b26-ca61-46c6-9e75-981cae435b2e',
    oracle_id: '079c46cc-feb0-4998-8593-c8b739afdb82',
    multiverse_ids: [],
    tcgplayer_id: 78621,
    name: 'Elephant',
    lang: 'en',
    released_at: '2001-01-01',
    uri:
     'https://api.scryfall.com/cards/540a3b26-ca61-46c6-9e75-981cae435b2e',
    scryfall_uri: 'https://scryfall.com/card/mpr/3/elephant?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/mpr/3.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/mpr/3.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/mpr/3.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/mpr/3.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/mpr/3.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/mpr/3.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Elephant',
    oracle_text: '',
    power: '3',
    toughness: '3',
    colors: [ 'G' ],
    color_identity: [ 'G' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'mpr',
    set_name: 'Magic Player Rewards 2001',
    set_uri:
     'https://api.scryfall.com/sets/84cd4f76-a638-41ac-8c60-3a82d8708b5c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ampr&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/mpr?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/540a3b26-ca61-46c6-9e75-981cae435b2e/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A079c46cc-feb0-4998-8593-c8b739afdb82&unique=prints',
    collector_number: '3',
    digital: false,
    rarity: 'common',
    flavor_text:
     "It's not slow. It's deciding whether to stomp you or gore you.",
    illustration_id: 'a98649a2-2c4f-414b-9f7c-24802fefd8f4',
    artist: 'Terese Nielsen',
    border_color: 'black',
    frame: '1997',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Elephant&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Elephant',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Elephant' },
    myId: 7 },
  { object: 'card',
    id: '61587ac5-0cfe-4e5d-baa2-c9a458e40474',
    oracle_id: '2b7dba01-b08c-4218-9fc1-da55559d9155',
    multiverse_ids: [],
    tcgplayer_id: 78629,
    name: 'Saproling',
    lang: 'en',
    released_at: '2001-01-01',
    uri:
     'https://api.scryfall.com/cards/61587ac5-0cfe-4e5d-baa2-c9a458e40474',
    scryfall_uri: 'https://scryfall.com/card/mpr/2/saproling?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/mpr/2.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/mpr/2.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/mpr/2.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/mpr/2.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/mpr/2.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/mpr/2.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Saproling',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [ 'G' ],
    color_identity: [ 'G' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       duel: 'not_legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'mpr',
    set_name: 'Magic Player Rewards 2001',
    set_uri:
     'https://api.scryfall.com/sets/84cd4f76-a638-41ac-8c60-3a82d8708b5c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ampr&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/mpr?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/61587ac5-0cfe-4e5d-baa2-c9a458e40474/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A2b7dba01-b08c-4218-9fc1-da55559d9155&unique=prints',
    collector_number: '2',
    digital: false,
    rarity: 'common',
    flavor_text:
     'The nauseating wriggling of a saproling is exceeded only by the nauseating wriggling of its prey.',
    illustration_id: '6efeac77-ee47-4957-8f60-a176b42c4609',
    artist: 'Jeff Laubenstein',
    border_color: 'black',
    frame: '1997',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Saproling&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Saproling',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Saproling' },
    myId: 8 },
  { object: 'card',
    id: '1b04fea2-ef5b-4311-bc52-8222f1501eac',
    oracle_id: '09a70ae8-3859-4a09-901d-dce063fa3b5f',
    multiverse_ids: [],
    tcgplayer_id: 38344,
    name: 'Wasteland',
    lang: 'en',
    released_at: '2001-01-01',
    uri:
     'https://api.scryfall.com/cards/1b04fea2-ef5b-4311-bc52-8222f1501eac',
    scryfall_uri: 'https://scryfall.com/card/mpr/1/wasteland?utm_source=api',
    layout: 'normal',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/front/1/b/1b04fea2-ef5b-4311-bc52-8222f1501eac.jpg?1552696939',
       normal:
        'https://img.scryfall.com/cards/normal/front/1/b/1b04fea2-ef5b-4311-bc52-8222f1501eac.jpg?1552696939',
       large:
        'https://img.scryfall.com/cards/large/front/1/b/1b04fea2-ef5b-4311-bc52-8222f1501eac.jpg?1552696939',
       png:
        'https://img.scryfall.com/cards/png/front/1/b/1b04fea2-ef5b-4311-bc52-8222f1501eac.png?1552696939',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/front/1/b/1b04fea2-ef5b-4311-bc52-8222f1501eac.jpg?1552696939',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/front/1/b/1b04fea2-ef5b-4311-bc52-8222f1501eac.jpg?1552696939' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Land',
    oracle_text:
     '{T}: Add {C}.\n{T}, Sacrifice Wasteland: Destroy target nonbasic land.',
    colors: [],
    color_identity: [],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'legal',
       pauper: 'not_legal',
       vintage: 'legal',
       penny: 'not_legal',
       commander: 'legal',
       duel: 'legal',
       oldschool: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: true,
    nonfoil: false,
    oversized: false,
    promo: true,
    reprint: true,
    set: 'mpr',
    set_name: 'Magic Player Rewards 2001',
    set_uri:
     'https://api.scryfall.com/sets/84cd4f76-a638-41ac-8c60-3a82d8708b5c',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Ampr&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/mpr?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/1b04fea2-ef5b-4311-bc52-8222f1501eac/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A09a70ae8-3859-4a09-901d-dce063fa3b5f&unique=prints',
    collector_number: '1',
    digital: false,
    rarity: 'rare',
    flavor_text:
     '"I will show you fear in a handful of dust." — T. S. Eliot, "The Waste Land"',
    illustration_id: '38cf1045-0520-4a67-a25e-dc7bb3acead6',
    artist: 'Una Fricker',
    border_color: 'black',
    frame: '1997',
    full_art: false,
    story_spotlight: false,
    edhrec_rank: 355,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Wasteland&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Wasteland',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Wasteland' },
    myId: 9 } ]