import React from 'react';
import styles from './Filters.css';

const TestSets = React.forwardRef((props, ref) => {

	const setArray = [
		{ name: 'Alpha Limited', id: 'lea' },
		{ name: 'Beta Limited', id: 'leb' },
		{ name: 'Unlimited', id: '2ed' },
		{ name: 'Arabian Nights', id: 'arn' },
		{ name: 'Antiquities', id: 'atq' },
		{ name: 'Revised Edition', id: '3ed' },
		{ name: 'Book Promos', id: 'phpr' },
		{ name: 'Legends', id: 'leg' },
		{ name: 'The Dark', id: 'drk' },
		{ name: 'Fallen Empires', id: 'fem' },
		{ name: 'Fourth Edition', id: '4ed' },
		{ name: 'Ice Age', id: 'ice' },
		{ name: 'Alliances', id: 'chr'},
		{ name: 'Coldsnap', id: 'ren'},
		{ name: 'Mirage', id: 'mir'},
		{ name: 'Visions', id: 'vis'},
		{ name: 'Fifth Edition', id: '5ed'},
		{ name: 'Portal', id: 'por'},
		{ name: 'Weatherlight', id: 'wth'},
		{ name: 'Tempest', id: 'tmp'},
		{ name: 'Stronghold', id: 'sth'},
		{ name: 'Exodus', id: 'exo'},
		{ name: 'Unglued', id: 'ugl'},
		{ name: "Urza's Saga", id: 'usg'},
		{ name: "Urza's Legacy", id: 'ulg'},
		{ name: "Sixth Edition", id: '6ed'},
		{ name: "Urza's Destiny", id: 'uds'},
		{ name: 'Mercadian Masques', id: 'mmq'},
		{ name: 'Nemesis', id: 'nem'},
		{ name: 'Prophecy', id: 'pcy'},
		{ name: "Seventh Edition", id: '7ed'},
		{ name: 'Apocalypse', id: 'inv'},
		{ name: 'Odyssey', id: 'ody'},
		{ name: 'Torment', id: 'tor'},
		{ name: 'Judgment', id: 'jud'},
		{ name: 'Onslaught', id: 'ons'},
		{ name: 'Legions', id: 'lgn'},
		{ name: 'Scourge', id: 'scg'},
		{ name: "Eighth Edition", id: '8ed'},
		{ name: 'Mirrodin', id: 'mrd'},
		{ name: 'Darksteel', id: 'dst'},
		{ name: 'Fifth Dawn', id: '5dn'},
		{ name: 'Champions of Kamigawa', id: 'chk'},
		{ name: 'Unhinged', id: 'unh'},
		{ name: 'Betrayers of Kamigawa', id: 'bok'},
		{ name: 'Saviors of Kamigawa', id: 'sok'},
		{ name: 'Ninth Edition', id: '9ed'},
		{ name: 'Ravnica: City of Guilds', id: 'rav'},
		{ name: 'Guildpact', id: 'gpt'},
		{ name: 'Dissension', id: 'dis'},
		{ name: 'Coldsnap', id: 'csp'},
		{ name: 'Time Spiral', id: 'tsp'},
		{ name: 'Planar Chaos', id: 'plc'},
		{ name: 'Future Sight', id: 'fut'},
		{ name: 'Tenth Edition', id: '10e'},
		{ name: 'Lorwyn', id: 'lrw'},
		{ name: 'Duel Decks: Elves vs Goblins', id: 'evg'},
		{ name: 'Morningtide', id: 'mor'},
		{ name: 'Shadowmoor', id: 'shm'},
		{ name: 'Eventide', id: 'eve'},
		{ name: 'From the Vault: Dragons', id: 'drb'},
		{ name: 'Shards of Alara', id: 'ala'},
		{ name: 'Duel Decks: Jace vs Chandra', id: 'dd2'},
		{ name: 'Conflux', id: 'con'},
		{ name: 'Duel Decks: Divine vs Demonic', id: 'ddc'},
		{ name: 'Alara Reborn', id: 'arb'},
		{ name: 'Magic 2010', id: 'm10'},
		{ name: 'From the Vault: Exiled', id: 'v09'},
		{ name: 'Planechase', id: 'hop'},
		{ name: 'Zendikar', id: 'zen'},
		{ name: 'Duel Decks: Garruk vs Liliana', id: 'ddd'},
		{ name: 'Premium Deck Series: Slivers', id: 'ho9' },
		{ name: 'Worldwake', id: 'wwk' },
		{ name: 'Duel Decks: Phyrexia vs The Coalition', id: 'dde' },
		{ name: 'Rise of the Eldrazi', id: 'roe' },
		{ name: 'Duels of the Planeswalkers', id: 'dpa' },
		{ name: 'Archenemy', id: 'arc' },
		{ name: 'Magic 2011', id: 'm11' },
		{ name: 'From the Vault: Relics', id: 'v10' },
		{ name: 'Duel Decks: Elspeth vs Tezzeret', id: 'ddf' },
		{ name: 'Scars of Mirrodin', id: 'som' },
		{ name: 'Mirrodin Besieged', id: 'mbs' },
		{ name: 'Duel Decks: Knights vs Dragons', id: 'ddg' },
		{ name: 'New Phyrexia', id: 'nph' },
		{ name: 'Magic 2012', id: 'm12' },
		{ name: 'From the Vault: Legends', id: 'v11' },
		{ name: 'Duel Decks: Ajani vs Nicol Bolas', id: 'ddh' },
		{ name: 'Innistrad', id: 'isd' },
		{ name: 'Dark Ascension', id: 'dka' },
		{ name: 'Duel Decks: Venser vs Koth', id: 'ddi' },
		{ name: 'Avacyn Restored', id: 'avr' },
		{ name: 'Magic 2013', id: 'm13' },
		{ name: 'From the Vault: Realms', id: 'v12' },
		{ name: 'Duel Decks: Izzet vs Golgari', id: 'ddj' },
		{ name: 'Return to Ravnica', id: 'rtr' },
		{ name: 'Duel Decks: Mirrodin Pure vs New Phyrexia', id: 'td2' },
		{ name: 'Gatecrash', id: 'gtc' },
		{ name: 'Duel Decks: Sorin vs Tibalt', id: 'ddk' },
		{ name: "Dragon's Maze", id: 'dgm' },
		{ name: 'Magic 2014', id: 'm14' },
		{ name: 'From the Vault: Twenty', id: 'v13' },
		{ name: 'Duel Decks: Heroes vs Monsters', id: 'ddl' },
		{ name: 'Theros', id: 'ths' },
		{ name: 'Commander 2013', id: 'c13' },
		{ name: 'Born of the Gods', id: 'bng' },
		{ name: 'Duel Decks: Jace vs Vraska', id: 'ddm' },
		{ name: 'Journey into Nyx', id: 'jou' },
		{ name: 'Conspiracy', id: 'cns' },
		{ name: 'Magic 2015', id: 'm15' },
		{ name: 'From the Vault: Annihilation', id: 'v14' },
		{ name: 'Duel Decks: Speed vs Cunning', id: 'ddn' },
		{ name: 'Khans of Tarkir', id: 'ktk' },
		{ name: 'Commander 2014', id: 'c14' },
		{ name: 'Duel Decks Anthology', id: 'dd3' },
		{ name: 'Fate Reforged', id: 'frf' },
		{ name: 'Duel Decks: Elspeth vs Kiora', id: 'ddo' },
		{ name: 'Dragons of Tarkir', id: 'dtk' },
		{ name: 'Tempest Remastered', id: 'tpr' },
		{ name: 'Modern Masters 2015', id: 'mm2' },
		{ name: 'Magic Origins', id: 'ori' },
		{ name: 'From the Vault: Angels', id: 'v15' },
		{ name: 'Duel Decks: Zendikar vs Eldrazi', id: 'ddp' },
		{ name: 'Battle for Zendikar', id: 'bfz' },
		{ name: 'Zendikar Expeditions', id: 'exp' },
		{ name: 'Commander 2015', id: 'c15' },
		{ name: 'Oath of the Gatewatch', id: 'ogw' },
		{ name: 'Duel Decks: Blessed vs Cursed', id: 'ddq' },
		{ name: 'Shadows Over Innistrad', id: 'soi' },
		{ name: 'Eternal Masters', id: 'ema' },
		{ name: 'Eldritch Moon', id: 'emn' },
		{ name: 'From the Vault: Lore', id: 'v16' },
		{ name: 'Conspiracy: Take the Crown', id: 'cn2' },
		{ name: 'Duel Decks: Nissa vs Ob Nixilis', id: 'ddr' },
		{ name: 'Kaladesh', id: 'kld' },
		{ name: 'Kaladesh Inventions', id: 'mps' },
		{ name: 'Commander 2016', id: 'c16' },
		{ name: 'Aether Revolt', id: 'aer' },
		{ name: 'Modern Masters 2017', id: 'mm3' },
		{ name: 'Duel Decks: Mind vs Might', id: 'dds' },
		{ name: 'Amonkhet', id: 'akh' },
		{ name: 'Amonkhet Invocations', id: 'mp2' },
		{ name: 'Commander Anthology', id: 'cma' },
		{ name: 'Archenemy: Nicol Bolas', id: 'e01' },
		{ name: 'Hour of Devastation', id: 'hou' },
		{ name: 'Commander 2017', id: 'c17' },
		{ name: 'Ixalan', id: 'xln' },
		{ name: 'Duel Decks: Merfolk vs Goblins', id: 'ddt' },
		{ name: 'Iconic Masters', id: 'ima' },
		{ name: 'Explorers of Ixalan', id: 'e02' },
		{ name: 'From the Vault: Transform', id: 'v17' },
		{ name: 'Unstable', id: 'ust' },
		{ name: 'Rivals of Ixalan', id: 'rix' },
		{ name: 'Masters 25', id: 'a25' },
		{ name: 'Duel Decks: Elves vs Inventors', id: 'ddu' },
		// { name: 'Challenger Decks', id: 'qo1' }, //need to double check code on this one
		{ name: 'Dominaria', id: 'dom' },
		{ name: 'Commander Anthology 2', id: 'cm2' },
		{ name: 'Battlebond', id: 'bbd' },
		{ name: 'Signature Spellbook: Jace', id: 'ss1' },
		{ name: 'Core Set 2019', id: 'm19' },
		{ name: 'Commander 2018', id: 'c18' },
		{ name: 'Guilds of Ravnica Mythic Edition', id: 'med' },
		{ name: 'Guilds of Ravnica', id: 'grn' },
		{ name: 'Guilds of Ravnica Guild Kits', id: 'gk1' },
		{ name: 'Ultimate Masters', id: 'uma' },
		{ name: 'Ravnica Allegiance Mythic Edition', id: 'med' },
		{ name: 'Ravnica Allegiance', id: 'rna' },
		{ name: 'Ravnica Allegiance Guild Kits', id: 'gk2' }

	]

	let list = setArray.map((elem, index) => {
		return <option key={index} value={elem.id}>{elem.name}</option>
	})


	return (
		<select className={styles.select} onChange={(event)=>props.handleFilter(event, 'set')} ref={ref}>
			<option default value="All">sets (all standard)</option>
			{list}
		</select>
	)
})

export default TestSets;
