module.exports = [ { object: 'card',
    id: 'bf9acfe1-de7a-48fe-aed3-28a72db6d1c0',
    oracle_id: '340aaeb6-cd18-4908-9729-8c53ab02c6f8',
    multiverse_ids: [],
    tcgplayer_id: 94692,
    name: 'Knight',
    lang: 'en',
    released_at: '2012-01-01',
    uri:
     'https://api.scryfall.com/cards/bf9acfe1-de7a-48fe-aed3-28a72db6d1c0',
    scryfall_uri: 'https://scryfall.com/card/l12/2/knight?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/l12/2.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/l12/2.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/l12/2.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/l12/2.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/l12/2.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/l12/2.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Knight',
    oracle_text: 'Vigilance',
    power: '2',
    toughness: '2',
    colors: [ 'W' ],
    color_identity: [ 'W' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       '1v1': 'not_legal',
       duel: 'not_legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: false,
    reprint: false,
    set: 'l12',
    set_name: 'League Tokens 2012',
    set_uri:
     'https://api.scryfall.com/sets/43730e1c-6389-4bff-a1a2-447c50002992',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Al12&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/l12?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/bf9acfe1-de7a-48fe-aed3-28a72db6d1c0/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A340aaeb6-cd18-4908-9729-8c53ab02c6f8&unique=prints',
    collector_number: '2',
    digital: false,
    rarity: 'common',
    illustration_id: '588d16ad-908c-46c3-925d-bbd1fdcc96a8',
    artist: 'Lucas Graciano',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Knight&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Knight',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Knight' },
    myId: 2 },
  { object: 'card',
    id: '062043de-a199-408d-8d77-09531ad38b16',
    oracle_id: '4465eff4-5851-4721-a248-866c686c2ab8',
    multiverse_ids: [],
    tcgplayer_id: 78417,
    name: 'Goblin',
    lang: 'en',
    released_at: '2012-01-01',
    uri:
     'https://api.scryfall.com/cards/062043de-a199-408d-8d77-09531ad38b16',
    scryfall_uri: 'https://scryfall.com/card/l12/1/goblin?utm_source=api',
    layout: 'token',
    highres_image: true,
    image_uris:
     { small:
        'https://img.scryfall.com/cards/small/en/l12/1.jpg?1517813031',
       normal:
        'https://img.scryfall.com/cards/normal/en/l12/1.jpg?1517813031',
       large:
        'https://img.scryfall.com/cards/large/en/l12/1.jpg?1517813031',
       png: 'https://img.scryfall.com/cards/png/en/l12/1.png?1517813031',
       art_crop:
        'https://img.scryfall.com/cards/art_crop/en/l12/1.jpg?1517813031',
       border_crop:
        'https://img.scryfall.com/cards/border_crop/en/l12/1.jpg?1517813031' },
    mana_cost: '',
    cmc: 0,
    type_line: 'Token Creature — Goblin',
    oracle_text: '',
    power: '1',
    toughness: '1',
    colors: [ 'R' ],
    color_identity: [ 'R' ],
    legalities:
     { standard: 'not_legal',
       future: 'not_legal',
       frontier: 'not_legal',
       modern: 'not_legal',
       legacy: 'not_legal',
       pauper: 'not_legal',
       vintage: 'not_legal',
       penny: 'not_legal',
       commander: 'not_legal',
       '1v1': 'not_legal',
       duel: 'not_legal',
       brawl: 'not_legal' },
    games: [ 'paper' ],
    reserved: false,
    foil: false,
    nonfoil: true,
    oversized: false,
    promo: false,
    reprint: true,
    set: 'l12',
    set_name: 'League Tokens 2012',
    set_uri:
     'https://api.scryfall.com/sets/43730e1c-6389-4bff-a1a2-447c50002992',
    set_search_uri:
     'https://api.scryfall.com/cards/search?order=set&q=e%3Al12&unique=prints',
    scryfall_set_uri: 'https://scryfall.com/sets/l12?utm_source=api',
    rulings_uri:
     'https://api.scryfall.com/cards/062043de-a199-408d-8d77-09531ad38b16/rulings',
    prints_search_uri:
     'https://api.scryfall.com/cards/search?order=released&q=oracleid%3A4465eff4-5851-4721-a248-866c686c2ab8&unique=prints',
    collector_number: '1',
    digital: false,
    rarity: 'common',
    illustration_id: 'cf19211e-6208-4512-b664-146499d8c45d',
    artist: 'Jim Nelson',
    border_color: 'black',
    frame: '2003',
    frame_effect: '',
    full_art: false,
    story_spotlight: false,
    related_uris:
     { tcgplayer_decks:
        'https://decks.tcgplayer.com/magic/deck/search?contains=Goblin&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall',
       edhrec: 'http://edhrec.com/route/?cc=Goblin',
       mtgtop8:
        'http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Goblin' },
    myId: 3 } ]